/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/04-action-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.action.action-group
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type { Meta, StoryObj } from "@storybook/react";
import { ActionGroup } from "./ActionGroup";
import type { ActionGroupProps } from "./ActionGroup.types";

const defaultArgs = {
  slot: "toolbar",
  actions: [{ type: "mutation", target: "scaffold.action", label: "Run action" }],
} as unknown as ActionGroupProps;

const meta = {
  title: "Admin DSL Widgets/Molecules/ActionGroup",
  component: ActionGroup,
  args: defaultArgs,
  parameters: {
    docs: {
      description: {
        component: "Render a list of actions with consistent spacing, wrapping, and slot-specific visual treatment.",
      },
    },
  },
} satisfies Meta<typeof ActionGroup>;

export default meta;
type Story = StoryObj<typeof meta>;

export const PageHeaderActions: Story = {
  name: "PageHeaderActions",
  parameters: { docs: { description: { story: "Tests the PageHeaderActions scenario for ActionGroup with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ActionGroup {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "pageHeaderActions"
}, asserts: [
  "ActionGroup renders the PageHeaderActions scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const PanelFooterActions: Story = {
  name: "PanelFooterActions",
  parameters: { docs: { description: { story: "Tests the PanelFooterActions scenario for ActionGroup with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ActionGroup {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "panelFooterActions"
}, asserts: [
  "ActionGroup renders the PanelFooterActions scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const RowActions: Story = {
  name: "RowActions",
  parameters: { docs: { description: { story: "Tests row-scoped actions in ActionGroup." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ActionGroup {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "rowActions"
}, asserts: [
  "ActionGroup renders the RowActions scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const BulkToolbarActions: Story = {
  name: "BulkToolbarActions",
  parameters: { docs: { description: { story: "Tests the BulkToolbarActions scenario for ActionGroup with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ActionGroup {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "bulkToolbarActions"
}, asserts: [
  "ActionGroup renders the BulkToolbarActions scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const FormFooterActions: Story = {
  name: "FormFooterActions",
  parameters: { docs: { description: { story: "Tests the FormFooterActions scenario for ActionGroup with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ActionGroup {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "formFooterActions"
}, asserts: [
  "ActionGroup renders the FormFooterActions scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const OverflowActions: Story = {
  name: "OverflowActions",
  parameters: { docs: { description: { story: "Tests compact overflow action presentation in ActionGroup." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ActionGroup {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "overflowActions"
}, asserts: [
  "ActionGroup renders the OverflowActions scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const WrappingMobile: Story = {
  name: "WrappingMobile",
  parameters: { docs: { description: { story: "Tests narrow-width wrapping behavior for ActionGroup." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ActionGroup {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "wrappingMobile"
}, asserts: [
  "ActionGroup renders the WrappingMobile scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
