/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T22:42:09+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/04-action-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: e4a9d9e 2026-05-18 HAIR-041 Step 63: Refresh action widget scaffolds
 * Widget ID: admin.action.action-group
 *
 * This file started as generated schema-v2 scaffold output. The implementation
 * below composes ActionButton and replaces the renderActions wrapper in
 * web/src/admin-dsl/render.tsx with a typed action-slot component.
 */
import type { CSSProperties } from "react";
import { ActionButton } from "../../atoms/ActionButton";
import { actionGroupWidgetMetadata } from "./ActionGroup.metadata";
import type { ActionGroupProps } from "./ActionGroup.types";

function justifyForAlign(align: ActionGroupProps["align"]): CSSProperties["justifyContent"] {
  if (align === "end") return "flex-end";
  if (align === "between") return "space-between";
  return "flex-start";
}

function sizeForSlot(slot: ActionGroupProps["slot"]): "sm" | "md" | "touch" {
  if (slot === "row" || slot === "rowOverflow" || slot === "panelFooter" || slot === "formFooter") return "sm";
  if (slot === "sidebarNav" || slot === "bulkToolbar") return "touch";
  return "md";
}

function variantForSlot(slot: ActionGroupProps["slot"]): "solid" | "soft" | "subtle" | "danger" | "overflow" | undefined {
  if (slot === "rowOverflow" || slot === "overflow") return "overflow";
  if (slot === "row" || slot === "panelFooter" || slot === "detail") return "subtle";
  return undefined;
}

export function ActionGroup<C = unknown>({
  id,
  className,
  style,
  dataAttributes,
  actions,
  context,
  slot,
  align = "start",
  onAction,
}: ActionGroupProps<C>) {
  if (!actions.length) return null;
  const dataAttrs = Object.fromEntries(
    Object.entries(dataAttributes ?? {}).map(([key, value]) => [`data-${key}`, String(value)]),
  ) as Record<string, string>;
  const variant = variantForSlot(slot);
  const size = sizeForSlot(slot);

  return (
    <div
      id={id}
      className={["adminDslActions", className].filter(Boolean).join(" ") || undefined}
      data-admin-dsl-widget-id={actionGroupWidgetMetadata.widgetId}
      data-admin-dsl-action-slot={slot}
      style={{
        display: "flex",
        gap: slot === "row" || slot === "rowOverflow" ? 6 : 8,
        flexWrap: "wrap",
        alignItems: "center",
        justifyContent: justifyForAlign(align),
        ...style,
      }}
      {...dataAttrs}
    >
      {actions.map((action, index) => (
        <ActionButton
          key={action.id || `${action.type}:${action.target}:${index}`}
          action={action}
          context={context as C}
          variant={variant}
          size={size}
          onAction={onAction}
        />
      ))}
    </div>
  );
}
