/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/04-action-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: ActionGroup
 * Category: action_widgets
 * Classification: {"level": "molecule"}
 * Current source inventory: renderActions wrapper in web/src/admin-dsl/render.tsx
 *
 * Purpose:
 * Render a list of actions with consistent spacing, wrapping, and slot-specific visual treatment.
 *
 * Human notes from YAML:
 * {
 *   "intent": "Provides the flex/wrap/alignment behavior for a slot of actions. It is the main bridge between semantic action slots and repeated ActionButton atoms.",
 *   "adapter_boundary": "Adapters should choose slot names such as pageHeader or bulkToolbar; the widget chooses spacing and presentation defaults for that slot.",
 *   "slot_intent": {
 *     "actions": "A group represents one semantic slot, not an arbitrary pile of buttons. The slot name should influence density, wrapping, and hierarchy."
 *   },
 *   "storybook_intent": "Stories should prove page-header, row, panel-footer, form-footer, overflow, and bulk-toolbar groups at desktop and mobile widths."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "actions",
 *     "notes": "Slot-specific list of actions rendered as ActionButton children.",
 *     "callback_prop": "onAction",
 *     "intent": "A group represents one semantic slot, not an arbitrary pile of buttons. The slot name should influence density, wrapping, and hierarchy.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Replace placeholder with ActionButton composition.
 * - XXX: Define exact wrapping rules for mobile and dense row contexts.
 */
// XXX: Replace generated defaultArgs with purposeful fixtures for every planned story before treating this as visual coverage.
import type { Meta, StoryObj } from "@storybook/react";
import { ActionGroup } from "./ActionGroup";
import type { ActionGroupProps } from "./ActionGroup.types";

const defaultArgs = {
  slot: "toolbar",
  actions: [{ type: "mutation", target: "scaffold.action", label: "Run action" }],
} as unknown as ActionGroupProps;

const meta = {
  title: "Admin DSL Widgets/Molecules/ActionGroup",
  component: ActionGroup,
  args: defaultArgs,
} satisfies Meta<typeof ActionGroup>;

export default meta;
type Story = StoryObj<typeof meta>;

export const PageHeaderActions: Story = {};
export const PanelFooterActions: Story = {};
export const RowActions: Story = {};
export const BulkToolbarActions: Story = {};
export const FormFooterActions: Story = {};
export const OverflowActions: Story = {};
export const WrappingMobile: Story = {};
