/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T01:30:30+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/07-data-display-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: baf8866 2026-05-18T17:21:36-04:00 HAIR-041 Step 50: Regenerate widget scaffolds from schema v2
 * Widget ID: admin.data-display.comparison-table
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

/**
 * Props for ComparisonTable. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface ComparisonTableRow {
  /**
   * Stable DOM/data id for the ComparisonTable instance.
   */
  id?: string;
  /**
   * field configures comparison table. Type: string.
   */
  field: string;
  /**
   * current configures comparison table. Type: string.
   */
  current?: string;
  /**
   * draft configures comparison table. Type: string.
   */
  draft?: string;
  /**
   * scheduled configures comparison table. Type: string.
   */
  scheduled?: string;
  /**
   * Ordered action list for the ComparisonTable slot. Presentation should be derived from semantic slot and action intent.
   */
  actions?: ActionViewModel[];
}

/**
 * Props for ComparisonTable. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface ComparisonTableProps extends CommonWidgetProps {
  /**
   * Stable table id used by ComparisonTable for selection state, action context, and test hooks.
   */
  tableId: string;
  /**
   * Row data rendered by ComparisonTable. Row-specific actions receive entries from this collection as context.
   */
  rows: ComparisonTableRow[];
  /**
   * empty configures comparison table. Type: React.ReactNode.
   */
  empty?: React.ReactNode;
  /**
   * Callback invoked by ComparisonTable with table id, row, and optional row id.
   */
  onRowAction?: (action: ActionViewModel, context: { tableId: string; row: ComparisonTableRow }) => void;
}
