/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T01:30:30+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/07-data-display-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.data-display.comparison-table
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for ComparisonTable.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const comparisonTableWidgetMetadata = {
  "widgetId": "admin.data-display.comparison-table",
  "name": "ComparisonTable",
  "category": "data_display_widgets",
  "classification": {
    "level": "organism",
    "description": "ComparisonTable participates in the Admin DSL component system as a organism; its level controls scaffold location and Storybook grouping."
  },
  "purpose": "ComparisonTable widget.",
  "designRationale": "ComparisonTable extracts a named React boundary from the old Admin DSL renderer so behavior, stories, styling, and action context can be reviewed independently.",
  "adapterBoundary": "The Admin DSL adapter should convert raw node props/actions into typed ComparisonTable props. ComparisonTable should not parse AdminNode JSON or call backend dispatch helpers directly.",
  "implementationNotes": [
    "Implement ComparisonTable using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure ComparisonTable exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "rowActions": {
      "doc": "rowActions action slot for ComparisonTable. The widget emits the declared context through onAction and adapters lower it to runtime dispatch.",
      "callback": "onAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "RowactionsContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Context described in v1 IR as: { tableId, row }"
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "Adapter lowers this typed callback into Admin DSL dispatch."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by ComparisonTable. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed ComparisonTable props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<ComparisonTable />"
    }
  },
  "stories": {
    "DefaultChanges": {
      "doc": "Tests the DefaultChanges scenario for ComparisonTable with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "defaultChanges"
      },
      "asserts": [
        "ComparisonTable renders the DefaultChanges scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "NoChangesEmptyState": {
      "doc": "Tests empty comparison/no-change state in ComparisonTable.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "noChangesEmptyState"
      },
      "asserts": [
        "ComparisonTable renders the NoChangesEmptyState scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "RowActions": {
      "doc": "Tests row-scoped actions in ComparisonTable.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "rowActions"
      },
      "asserts": [
        "ComparisonTable renders the RowActions scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "MobileCards": {
      "doc": "Tests mobile card adaptation for ComparisonTable.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "mobileCards"
      },
      "asserts": [
        "ComparisonTable renders the MobileCards scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "LongValues": {
      "doc": "Tests long before/after values and responsive wrapping in ComparisonTable.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "longValues"
      },
      "asserts": [
        "ComparisonTable renders the LongValues scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"comparisonTable\""
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;
