/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T00:32:12+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.layout.filter-bar
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for FilterBar.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const filterBarWidgetMetadata = {
  "widgetId": "admin.layout.filter-bar",
  "name": "FilterBar",
  "category": "layout_widgets",
  "classification": {
    "level": "molecule",
    "description": "FilterBar participates in the Admin DSL component system as a molecule; its level controls scaffold location and Storybook grouping."
  },
  "purpose": "Represents filter chips/pills as a specific action context rather than generic tabs or buttons.",
  "designRationale": "Represents filter chips/pills as a specific action context rather than generic tabs or buttons.",
  "adapterBoundary": "Adapter maps filter list/value/action; widget emits selected filter context.",
  "implementationNotes": [
    "Implement FilterBar using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure FilterBar exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "filterChange": {
      "doc": "Filter actions carry the chosen filter object so backend or frontend state can update consistently.",
      "callback": "onFilterChange",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "FilterchangeContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the filterChange slot on FilterBar."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by FilterBar. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed FilterBar props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<FilterBar />"
    }
  },
  "stories": {
    "Default": {
      "doc": "Tests the baseline FilterBar rendering with representative production-like data.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "default"
      },
      "asserts": [
        "FilterBar renders the Default scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "ActiveFilter": {
      "doc": "Tests the ActiveFilter scenario for FilterBar with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "activeFilter"
      },
      "asserts": [
        "FilterBar renders the ActiveFilter scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "ManyFiltersWrap": {
      "doc": "Tests the ManyFiltersWrap scenario for FilterBar with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "manyFiltersWrap"
      },
      "asserts": [
        "FilterBar renders the ManyFiltersWrap scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "Readonly": {
      "doc": "Tests the Readonly scenario for FilterBar with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "readonly"
      },
      "asserts": [
        "FilterBar renders the Readonly scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    },
    {
      "id": "keep-raw-admin-dsl-json-parsing-in-adapters-not-in-this-widget",
      "severity": "recommended",
      "doc": "Keep raw Admin DSL JSON parsing in adapters, not in this widget."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"filterBar\""
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;
