/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: ResourceTable
 * Category: resource_widgets
 * Classification: {"level": "organism"}
 * Current source inventory: case "resourceTable", renderTableCell, bulk bar, pagination, and mobile table CSS in responsiveCss
 *
 * Purpose:
 * Render semantic resource rows as a desktop table and mobile card list. This is the most important information-dense Admin DSL widget.
 *
 * Human notes from YAML:
 * {
 *   "intent": "Primary dense data organism. It owns desktop table/mobile card behavior, selection, row actions, bulk actions, empty state, and pagination composition.",
 *   "adapter_boundary": "Adapter reads current Admin DSL columns/rows/actions and turns placements into rowActions, rowOverflow, bulkActions, and pagination actions.",
 *   "slot_intent": {
 *     "rowActions": "Row actions receive table and row context.",
 *     "rowOverflow": "Overflow is row-scoped but compact and menu-oriented.",
 *     "bulkToolbar": "Bulk actions receive table, visible/selected scope, rows, and selected IDs.",
 *     "pagination": "Pagination actions receive page/total context."
 *   },
 *   "storybook_intent": "Stories should be the canonical visual harness for dense admin tables, including mobile cards and contextual action payloads."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "rowActions",
 *     "context": "{ tableId, row, rowId }",
 *     "callback_prop": "onRowAction",
 *     "intent": "Row actions receive table and row context.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   },
 *   {
 *     "name": "rowOverflow",
 *     "context": "{ tableId, row, rowId }",
 *     "callback_prop": "onRowAction",
 *     "intent": "Overflow is row-scoped but compact and menu-oriented.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   },
 *   {
 *     "name": "bulkToolbar",
 *     "context": "{ tableId, scope, rows, selectedRowIds }",
 *     "callback_prop": "onBulkAction",
 *     "intent": "Bulk actions receive table, visible/selected scope, rows, and selected IDs.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   },
 *   {
 *     "name": "pagination",
 *     "context": "table/page",
 *     "callback_prop": "onAction",
 *     "intent": "Pagination actions receive page/total context.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Replace placeholder with desktop table plus mobile card implementation.
 * - XXX: Wire real selection state and row/bulk callback contexts.
 */
// XXX: Replace generated defaultArgs with purposeful fixtures for every planned story before treating this as visual coverage.
import type { Meta, StoryObj } from "@storybook/react";
import { ResourceTable } from "./ResourceTable";
import type { ResourceTableProps } from "./ResourceTable.types";

const defaultArgs = {
  tableId: "requests",
  columns: [
    { id: "customer", label: "Customer", kind: "text", primary: true },
    { id: "status", label: "Status", kind: "badge" },
  ],
  rows: [
    { id: "req_1", customer: "Maya Chen", status: "new" },
    { id: "req_2", customer: "Jules Park", status: "needsInfo" },
  ],
  selectable: true,
  bulkActions: [{ type: "mutation", target: "requests.assign", label: "Assign" }],
} as unknown as ResourceTableProps;

const meta = {
  title: "Admin DSL Widgets/Organisms/ResourceTable",
  component: ResourceTable,
  args: defaultArgs,
} satisfies Meta<typeof ResourceTable>;

export default meta;
type Story = StoryObj<typeof meta>;

export const DefaultRows: Story = {};
export const SelectableWithBulkToolbar: Story = {};
export const RowActions: Story = {};
export const OverflowActions: Story = {};
export const EmptyState: Story = {};
export const Pagination: Story = {};
export const StatusBadgeCells: Story = {};
export const DragHandleColumn: Story = {};
export const MobileCards: Story = {};
export const LongTextAndDenseRows: Story = {};
export const ActionDispatchContexts: Story = {};
