/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.resource.resource-table
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type { ReactNode } from "react";
import type { ResourceTableProps } from "./ResourceTable.types";

const diagnostics = {
  "widgetId": "admin.resource.resource-table",
  "purpose": "Render semantic resource rows as a desktop table and mobile card list. This is the most important information-dense Admin DSL widget.",
  "adapterBoundary": "Adapter reads current Admin DSL columns/rows/actions and turns placements into rowActions, rowOverflow, bulkActions, and pagination actions.",
  "implementationNotes": [
    "Implement ResourceTable using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure ResourceTable exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "rowActions": {
      "doc": "Row actions receive table and row context.",
      "callback": "onRowAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "RowactionsContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Context described in v1 IR as: { tableId, row, rowId }"
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    },
    "rowOverflow": {
      "doc": "Overflow is row-scoped but compact and menu-oriented.",
      "callback": "onRowAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "RowoverflowContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Context described in v1 IR as: { tableId, row, rowId }"
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    },
    "bulkToolbar": {
      "doc": "Bulk actions receive table, visible/selected scope, rows, and selected IDs.",
      "callback": "onBulkAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "BulktoolbarContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Context described in v1 IR as: { tableId, scope, rows, selectedRowIds }"
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    },
    "pagination": {
      "doc": "Pagination actions receive page/total context.",
      "callback": "onAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "PaginationContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Context described in v1 IR as: table/page"
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    }
  },
  "examples": {
    "DefaultUsage": {
      "doc": "Demonstrates the intended normalized usage of ResourceTable after adapter lowering.",
      "demonstrates": [
        "Normalized props for ResourceTable.",
        "Adapter boundary expectations."
      ],
      "code": "<ResourceTable\n  tableId=\"requests\"\n  columns={requestColumns}\n  rows={requestRows}\n  selectable\n  bulkLabel=\"3 visible requests\"\n  bulkActions={[assignAction]}\n  onRowAction={(action, ctx) => dispatch(action, ctx)}\n  onBulkAction={(action, ctx) => dispatch(action, ctx)}\n/>"
    }
  },
  "implementationTodos": [
    {
      "id": "replace-placeholder-with-desktop-table-plus-mobile-card-implemen",
      "severity": "required",
      "doc": "Replace placeholder with desktop table plus mobile card implementation."
    },
    {
      "id": "wire-real-selection-state-and-row-bulk-callback-contexts",
      "severity": "recommended",
      "doc": "Wire real selection state and row/bulk callback contexts."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"resourceTable\", renderTableCell, bulk bar, pagination, and mobile table CSS in responsiveCss"
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;

/**
 * Scaffold for `ResourceTable`.
 *
 * Purpose: Render semantic resource rows as a desktop table and mobile card list. This is the most important information-dense Admin DSL widget.
 *
 * Adapter boundary: Adapter reads current Admin DSL columns/rows/actions and turns placements into rowActions, rowOverflow, bulkActions, and pagination actions.
 */
export function ResourceTable(props: ResourceTableProps) {
  const scaffoldProps = props as ResourceTableProps & {
    id?: string;
    className?: string;
    style?: React.CSSProperties;
    dataAttributes?: Record<string, string | number | boolean>;
    children?: ReactNode;
    main?: ReactNode;
    title?: string;
    label?: string;
    name?: string;
    value?: unknown;
  };
  const heading = scaffoldProps.title || scaffoldProps.label || scaffoldProps.name || "ResourceTable";
  const dataAttributes = Object.fromEntries(
    Object.entries(scaffoldProps.dataAttributes ?? {}).map(([key, value]) => [`data-${key}`, String(value)]),
  ) as Record<string, string>;

  return (
    <section
      id={scaffoldProps.id}
      className={scaffoldProps.className}
      data-admin-dsl-widget="ResourceTable"
      data-admin-dsl-widget-id="admin.resource.resource-table"
      data-admin-dsl-widget-level="organism"
      style={scaffoldProps.style}
      {...dataAttributes}
    >
      <div style={{ border: "1px solid #dfd2bd", borderRadius: 12, padding: 12, background: "#fffaf0" }}>
        <strong>{heading}</strong>
        <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>{diagnostics.purpose}</p>
        {diagnostics.adapterBoundary ? (
          <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>Adapter: {diagnostics.adapterBoundary}</p>
        ) : null}
        <details style={{ marginTop: 10, fontSize: 12, color: "#6f6254" }}>
          <summary>Widget IR diagnostics</summary>
          <pre style={{ whiteSpace: "pre-wrap", margin: "8px 0 0" }}>{JSON.stringify(diagnostics, null, 2)}</pre>
        </details>
      </div>
      {scaffoldProps.children ? <div style={{ marginTop: 12 }}>{scaffoldProps.children}</div> : null}
      {scaffoldProps.main ? <div style={{ marginTop: 12 }}>{scaffoldProps.main}</div> : null}
    </section>
  );
}
