/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: ResourceTable
 * Category: resource_widgets
 * Classification: {"level": "organism"}
 * Current source inventory: case "resourceTable", renderTableCell, bulk bar, pagination, and mobile table CSS in responsiveCss
 *
 * Purpose:
 * Render semantic resource rows as a desktop table and mobile card list. This is the most important information-dense Admin DSL widget.
 *
 * Human notes from YAML:
 * {
 *   "intent": "Primary dense data organism. It owns desktop table/mobile card behavior, selection, row actions, bulk actions, empty state, and pagination composition.",
 *   "adapter_boundary": "Adapter reads current Admin DSL columns/rows/actions and turns placements into rowActions, rowOverflow, bulkActions, and pagination actions.",
 *   "slot_intent": {
 *     "rowActions": "Row actions receive table and row context.",
 *     "rowOverflow": "Overflow is row-scoped but compact and menu-oriented.",
 *     "bulkToolbar": "Bulk actions receive table, visible/selected scope, rows, and selected IDs.",
 *     "pagination": "Pagination actions receive page/total context."
 *   },
 *   "storybook_intent": "Stories should be the canonical visual harness for dense admin tables, including mobile cards and contextual action payloads."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "rowActions",
 *     "context": "{ tableId, row, rowId }",
 *     "callback_prop": "onRowAction",
 *     "intent": "Row actions receive table and row context.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   },
 *   {
 *     "name": "rowOverflow",
 *     "context": "{ tableId, row, rowId }",
 *     "callback_prop": "onRowAction",
 *     "intent": "Overflow is row-scoped but compact and menu-oriented.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   },
 *   {
 *     "name": "bulkToolbar",
 *     "context": "{ tableId, scope, rows, selectedRowIds }",
 *     "callback_prop": "onBulkAction",
 *     "intent": "Bulk actions receive table, visible/selected scope, rows, and selected IDs.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   },
 *   {
 *     "name": "pagination",
 *     "context": "table/page",
 *     "callback_prop": "onAction",
 *     "intent": "Pagination actions receive page/total context.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Replace placeholder with desktop table plus mobile card implementation.
 * - XXX: Wire real selection state and row/bulk callback contexts.
 */
// XXX: Review this generated prop contract against the final widget implementation before relying on it as stable API.
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  PageActionHandler,
  PanelActionHandler,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

export type ResourceTableColumnKind =
  | "text"
  | "badge"
  | "boolean"
  | "dragHandle"
  | "actions"
  | "overflowActions"
  | "money"
  | "relativeTime";

export interface ResourceTableColumn<Row = Record<string, unknown>> {
  id: string;
  accessor?: keyof Row | string;
  label?: string;
  kind?: ResourceTableColumnKind;
  primary?: boolean;
  tone?: string;
  width?: number | string;
  map?: Record<string, { label: string; tone?: string }>;
}

export interface ResourceTableProps<Row = Record<string, unknown>> extends CommonWidgetProps {
  tableId: string;
  columns: ResourceTableColumn<Row>[];
  rows: Row[];
  selectable?: boolean;
  selectedRowIds?: string[];
  bulkLabel?: string;
  empty?: React.ReactNode;
  rowActions?: ActionViewModel[];
  bulkActions?: ActionViewModel[];
  pagination?: {
    page: number;
    total: number;
    actions?: ActionViewModel[];
  };
  onRowAction?: TableRowActionHandler<Row>;
  onBulkAction?: TableBulkActionHandler<Row>;
  onSelectionChange?: (context: { tableId: string; selectedRowIds: string[] }) => void;
}
