/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.resource.resource-table
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

/**
 * Props for ResourceTable. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface ResourceTableColumn<Row = Record<string, unknown>> {
  /**
   * Stable DOM/data id for the ResourceTable instance.
   */
  id: string;
  /**
   * accessor configures resource table. Type: keyof Row | string.
   */
  accessor?: keyof Row | string;
  /**
   * Human-readable label rendered by ResourceTable.
   */
  label?: string;
  /**
   * kind configures resource table. Type: ResourceTableColumnKind.
   */
  kind?: ResourceTableColumnKind;
  /**
   * primary configures resource table. Type: boolean.
   */
  primary?: boolean;
  /**
   * Visual tone used for status, emphasis, or border treatment in ResourceTable.
   */
  tone?: string;
  /**
   * width configures resource table. Type: number | string.
   */
  width?: number | string;
  /**
   * map configures resource table. Type: Record<string, { label: string; tone?: string }>.
   */
  map?: Record<string, { label: string; tone?: string }>;
}

/**
 * Props for ResourceTable. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface ResourceTableProps<Row = Record<string, unknown>> extends CommonWidgetProps {
  /**
   * Stable table id used by ResourceTable for selection state, action context, and test hooks.
   */
  tableId: string;
  /**
   * Column definitions that tell ResourceTable how to label, access, and render row values.
   */
  columns: ResourceTableColumn<Row>[];
  /**
   * Row data rendered by ResourceTable. Row-specific actions receive entries from this collection as context.
   */
  rows: Row[];
  /**
   * Whether ResourceTable exposes row selection and bulk-toolbar behavior.
   */
  selectable?: boolean;
  /**
   * Currently selected row ids for controlled selection behavior in ResourceTable.
   */
  selectedRowIds?: string[];
  /**
   * Label describing the current bulk-action scope in ResourceTable.
   */
  bulkLabel?: string;
  /**
   * empty configures resource table. Type: React.ReactNode.
   */
  empty?: React.ReactNode;
  /**
   * Actions that operate on an individual row in ResourceTable.
   */
  rowActions?: ActionViewModel[];
  /**
   * Actions that operate on selected or visible rows in ResourceTable.
   */
  bulkActions?: ActionViewModel[];
  /**
   * Paging state and navigation actions for ResourceTable.
   */
  pagination?: Record<string, unknown>;
  /**
   * page configures resource table. Type: number.
   */
  page: number;
  /**
   * total configures resource table. Type: number.
   */
  total: number;
  /**
   * Ordered action list for the ResourceTable slot. Presentation should be derived from semantic slot and action intent.
   */
  actions?: ActionViewModel[];
  /**
   * Callback invoked by ResourceTable with table id, row, and optional row id.
   */
  onRowAction?: TableRowActionHandler<Row>;
  /**
   * Callback invoked by ResourceTable with table id, selected ids, scope, and row data.
   */
  onBulkAction?: TableBulkActionHandler<Row>;
  /**
   * Callback emitted when ResourceTable row selection changes.
   */
  onSelectionChange?: (context: { tableId: string; selectedRowIds: string[] }) => void;
}
