/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T01:30:30+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/08-media-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.media.image-grid
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for ImageGrid.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const imageGridWidgetMetadata = {
  "widgetId": "admin.media.image-grid",
  "name": "ImageGrid",
  "category": "media_widgets",
  "classification": {
    "level": "organism",
    "description": "ImageGrid participates in the Admin DSL component system as a organism; its level controls scaffold location and Storybook grouping."
  },
  "purpose": "ImageGrid widget.",
  "designRationale": "ImageGrid extracts a named React boundary from the old Admin DSL renderer so behavior, stories, styling, and action context can be reviewed independently.",
  "adapterBoundary": "The Admin DSL adapter should convert raw node props/actions into typed ImageGrid props. ImageGrid should not parse AdminNode JSON or call backend dispatch helpers directly.",
  "implementationNotes": [
    "Implement ImageGrid using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure ImageGrid exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "cardAction": {
      "doc": "Future slot; no action in current renderer.",
      "callback": "onAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "CardactionContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the cardAction slot on ImageGrid."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "Adapter lowers this typed callback into Admin DSL dispatch."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by ImageGrid. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed ImageGrid props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<ImageGrid />"
    }
  },
  "stories": {
    "Default": {
      "doc": "Tests the baseline ImageGrid rendering with representative production-like data.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "default"
      },
      "asserts": [
        "ImageGrid renders the Default scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "WithStatuses": {
      "doc": "Tests the WithStatuses scenario for ImageGrid with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "withStatuses"
      },
      "asserts": [
        "ImageGrid renders the WithStatuses scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "Empty": {
      "doc": "Tests empty data handling for ImageGrid.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "empty"
      },
      "asserts": [
        "ImageGrid renders the Empty scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "ResponsiveGrid": {
      "doc": "Tests responsive grid behavior for ImageGrid.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "responsiveGrid"
      },
      "asserts": [
        "ImageGrid renders the ResponsiveGrid scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"imageGrid\""
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;
