/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/08-media-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.media.image-grid
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type { Meta, StoryObj } from "@storybook/react";
import { ImageGrid } from "./ImageGrid";
import type { ImageGridProps } from "./ImageGrid.types";

const defaultArgs = {
  items: [{ id: "photo_1", title: "Front", url: "/placeholder.png" }],
} as unknown as ImageGridProps;

const meta = {
  title: "Admin DSL Widgets/Organisms/ImageGrid",
  component: ImageGrid,
  args: defaultArgs,
  parameters: {
    docs: {
      description: {
        component: "ImageGrid widget.",
      },
    },
  },
} satisfies Meta<typeof ImageGrid>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Default",
  parameters: { docs: { description: { story: "Tests the baseline ImageGrid rendering with representative production-like data." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ImageGrid {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "default"
}, asserts: [
  "ImageGrid renders the Default scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const WithStatuses: Story = {
  name: "WithStatuses",
  parameters: { docs: { description: { story: "Tests the WithStatuses scenario for ImageGrid with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ImageGrid {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "withStatuses"
}, asserts: [
  "ImageGrid renders the WithStatuses scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const Empty: Story = {
  name: "Empty",
  parameters: { docs: { description: { story: "Tests empty data handling for ImageGrid." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ImageGrid {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "empty"
}, asserts: [
  "ImageGrid renders the Empty scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const ResponsiveGrid: Story = {
  name: "ResponsiveGrid",
  parameters: { docs: { description: { story: "Tests responsive grid behavior for ImageGrid." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <ImageGrid {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "responsiveGrid"
}, asserts: [
  "ImageGrid renders the ResponsiveGrid scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
