/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/08-media-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.media.image-gallery
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

/**
 * Props for ImageGallery. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface GalleryImage {
  /**
   * Stable DOM/data id for the ImageGallery instance.
   */
  id?: string;
  /**
   * Semantic action slot rendered by ImageGallery; this controls spacing, hierarchy, and default presentation.
   */
  slot?: string;
  /**
   * Primary heading or title rendered by ImageGallery.
   */
  title?: string;
  /**
   * Optional secondary heading text rendered by ImageGallery.
   */
  subtitle?: string;
  /**
   * status configures image gallery. Type: string.
   */
  status?: string;
  /**
   * Visual tone used for status, emphasis, or border treatment in ImageGallery.
   */
  tone?: string;
  /**
   * External or internal URL rendered by ImageGallery.
   */
  url?: string;
  /**
   * alt configures image gallery. Type: string.
   */
  alt?: string;
}

/**
 * Props for ImageGallery. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface ImageGalleryProps extends CommonWidgetProps {
  /**
   * galleryId configures image gallery. Type: string.
   */
  galleryId: string;
  /**
   * Image entries rendered by ImageGallery.
   */
  images: GalleryImage[];
  /**
   * emptyText configures image gallery. Type: string.
   */
  emptyText?: string;
  /**
   * imageAction configures image gallery. Type: ActionViewModel.
   */
  imageAction?: ActionViewModel;
  /**
   * onImageAction configures image gallery. Type: (action: ActionViewModel, context: { galleryId: string; image: GalleryImage }) => void.
   */
  onImageAction?: (action: ActionViewModel, context: { galleryId: string; image: GalleryImage }) => void;
}
