/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/07-data-display-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.data-display.status-text
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type { Meta, StoryObj } from "@storybook/react";
import { StatusText } from "./StatusText";
import type { StatusTextProps } from "./StatusText.types";

const defaultArgs = {
  label: "Published",
  tone: "success",
} as unknown as StatusTextProps;

const meta = {
  title: "Admin DSL Widgets/Atoms/StatusText",
  component: StatusText,
  args: defaultArgs,
  parameters: {
    docs: {
      description: {
        component: "StatusText widget.",
      },
    },
  },
} satisfies Meta<typeof StatusText>;

export default meta;
type Story = StoryObj<typeof meta>;

export const NeutralText: Story = {
  name: "NeutralText",
  parameters: { docs: { description: { story: "Tests the NeutralText scenario for StatusText with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <StatusText {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "neutralText"
}, asserts: [
  "StatusText renders the NeutralText scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const SuccessText: Story = {
  name: "SuccessText",
  parameters: { docs: { description: { story: "Tests the SuccessText scenario for StatusText with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <StatusText {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "successText"
}, asserts: [
  "StatusText renders the SuccessText scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const WarningText: Story = {
  name: "WarningText",
  parameters: { docs: { description: { story: "Tests the WarningText scenario for StatusText with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <StatusText {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "warningText"
}, asserts: [
  "StatusText renders the WarningText scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const DangerText: Story = {
  name: "DangerText",
  parameters: { docs: { description: { story: "Tests the DangerText scenario for StatusText with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <StatusText {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "dangerText"
}, asserts: [
  "StatusText renders the DangerText scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const PillVariant: Story = {
  name: "PillVariant",
  parameters: { docs: { description: { story: "Tests the PillVariant scenario for StatusText with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <StatusText {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "pillVariant"
}, asserts: [
  "StatusText renders the PillVariant scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const MappedFromTableValue: Story = {
  name: "MappedFromTableValue",
  parameters: { docs: { description: { story: "Tests the MappedFromTableValue scenario for StatusText with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <StatusText {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "mappedFromTableValue"
}, asserts: [
  "StatusText renders the MappedFromTableValue scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
