/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T04:13:24+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/10a-form-field-widgets.yaml
 * Widget ID: admin.form-field.select-field
 *
 * Manual edits after generation:
 * - 2026-05-19 / HAIR-041 Step 125: Added select stories for option, placeholder, error, disabled, mobile, and callback-probe states.
 */
import { useState } from "react";
import type { Meta, StoryObj } from "@storybook/react";
import { SelectField } from "./SelectField";
import type { SelectFieldOption } from "./SelectField.types";

const serviceOptions: SelectFieldOption[] = [
  { value: "cut", label: "Cut and finish" },
  { value: "color", label: "Dimensional color" },
  { value: "extensions", label: "Extensions consultation" },
  { value: "archived", label: "Archived import option", disabled: true },
];

function ChangeProbe() {
  const [last, setLast] = useState("No selection yet.");
  return <div><SelectField name="serviceType" label="Service type" value="cut" options={serviceOptions} onValueChange={(value) => setLast(value)} /><output style={{ display: "block", marginTop: 12, padding: 10, border: "1px solid #dfd2bd" }}>{last}</output></div>;
}

const meta = { title: "Admin DSL Widgets/Molecules/SelectField", component: SelectField } satisfies Meta<typeof SelectField>;
export default meta;
type Story = StoryObj<typeof SelectField>;

export const Default: Story = { args: { name: "serviceType", label: "Service type", value: "color", options: serviceOptions } };
export const WithPlaceholder: Story = { args: { name: "stylist", label: "Preferred stylist", value: "", placeholder: "Choose a stylist", required: true, options: [{ value: "ava", label: "Ava" }, { value: "mika", label: "Mika" }, { value: "jules", label: "Jules" }] } };
export const WithHelp: Story = { args: { name: "visibility", label: "Booking visibility", value: "public", helpText: "Controls whether customers can book this service online.", options: [{ value: "public", label: "Public" }, { value: "private", label: "Private" }, { value: "staff", label: "Staff only" }] } };
export const WithError: Story = { args: { name: "serviceType", label: "Service type", value: "", placeholder: "Choose service type", required: true, error: "Choose a service type before publishing.", options: serviceOptions } };
export const Disabled: Story = { args: { name: "importSource", label: "Import source", value: "square", disabled: true, helpText: "Managed by the connected catalog.", options: [{ value: "square", label: "Square catalog" }, { value: "manual", label: "Manual" }] } };
export const ChangeCallbackProbe: Story = { render: () => <ChangeProbe /> };
export const Mobile: Story = { parameters: { viewport: { defaultViewport: "mobile1" } }, args: { name: "mobileServiceType", label: "Long customer-facing service category selector", value: "extensions", helpText: "This select remains touch-friendly on narrow admin screens.", options: serviceOptions } };
