/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T04:13:24+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/10a-form-field-widgets.yaml
 * Source YAML last commit: a43c249 2026-05-19T00:12:12-04:00 HAIR-041 Step 124: Promote TextareaField
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.form-field.select-field
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for SelectField.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const selectFieldWidgetMetadata = {
  "widgetId": "admin.form-field.select-field",
  "name": "SelectField",
  "category": "form_field_widgets",
  "classification": {
    "level": "molecule",
    "description": "SelectField participates in the Admin DSL field system as a molecule; it extracts selectField behavior from FieldPreview."
  },
  "purpose": "Select control for enumerated values.",
  "designRationale": "SelectField creates a typed field boundary so label/error styling and input semantics can be reviewed independently.",
  "adapterBoundary": "The Admin DSL adapter converts raw field node props into typed SelectField props; the widget does not import AdminNode or dispatch helpers.",
  "implementationNotes": [
    "Preserve uncontrolled defaultValue/defaultChecked behavior unless a future form-session task explicitly moves fields to controlled state.",
    "Use FieldShell for label/help/error chrome where the widget renders a concrete control."
  ],
  "accessibilityNotes": [
    "Associate labels, descriptions, and errors with the underlying input using stable ids.",
    "Preserve native keyboard behavior for the field control."
  ],
  "actionSlots": {
    "valueChange": {
      "doc": "Optional typed callback emitted by SelectField; adapters may lower it only when the DSL declares an action.",
      "callback": "onValueChange",
      "action_type": "ActionViewModel",
      "cardinality": "zero_or_one",
      "context_type": "FieldValueChangeContext",
      "context": {
        "name": {
          "type": "string",
          "required": true,
          "doc": "Field name."
        },
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Current field value or action payload."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "Adapter-owned; not all field changes dispatch backend actions."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates normalized SelectField props after adapter lowering.",
      "demonstrates": [
        "Typed props without raw Admin DSL parsing.",
        "Shared field chrome and accessibility wiring."
      ],
      "code": "<SelectField name=\"label\" label=\"Label\" />"
    }
  },
  "stories": {
    "Default": {
      "doc": "Baseline production-like SelectField rendering.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "default"
      },
      "asserts": [
        "SelectField renders its visible label and current value/state."
      ]
    },
    "WithHelp": {
      "doc": "Helper text remains associated with SelectField.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "withHelp"
      },
      "asserts": [
        "Help text is visible and associated with the input."
      ]
    },
    "WithError": {
      "doc": "Validation error state is visible and accessible for SelectField.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "withError"
      },
      "asserts": [
        "Error text is visible and associated with the input."
      ]
    },
    "DisabledOrReadOnly": {
      "doc": "Disabled/read-only states are visible for SelectField.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "disabledOrReadOnly"
      },
      "asserts": [
        "Disabled/read-only state is visible."
      ]
    },
    "Mobile": {
      "doc": "SelectField remains usable in narrow containers.",
      "viewport": "mobile",
      "fixtures": {
        "scenario": "mobile"
      },
      "asserts": [
        "The field remains readable and touch-friendly."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "scaffold-and-promote-field-widget",
      "severity": "required",
      "doc": "Create typed implementation, hand-authored stories, renderer adapter mapping, validation, diary, and changelog."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "selectField"
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Legacy FieldPreview branch and form-field adapter source."
      }
    ]
  }
} as const;
