// Code generated by logcopter-gen; DO NOT EDIT.

package clients

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.hair-booking.pkg.clients")
