// Code generated by logcopter-gen; DO NOT EDIT.

package cmds

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.hair-booking.cmd.hair-booking.cmds")
