/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T00:32:12+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.layout.panel
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for Panel.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const panelWidgetMetadata = {
  "widgetId": "admin.layout.panel",
  "name": "Panel",
  "category": "layout_widgets",
  "classification": {
    "level": "organism",
    "description": "Panel participates in the Admin DSL component system as a organism; its level controls scaffold location and Storybook grouping."
  },
  "purpose": "Central admin surface primitive for dense workbench content. It owns header/body/footer chrome, padding, density, and action placement.",
  "designRationale": "Central admin surface primitive for dense workbench content. It owns header/body/footer chrome, padding, density, and action placement.",
  "adapterBoundary": "Adapter maps toolbarActions/footerActions and renders children separately; widget receives typed React children and action arrays.",
  "implementationNotes": [
    "Implement Panel using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure Panel exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "toolbarActions": {
      "doc": "Toolbar actions are local to the panel header and usually secondary.",
      "callback": "onToolbarAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "ToolbaractionsContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Context described in v1 IR as: panel"
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    },
    "footerActions": {
      "doc": "Footer actions are local to the panel result/flow and should preserve panel context.",
      "callback": "onFooterAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "FooteractionsContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Context described in v1 IR as: panel"
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    }
  },
  "examples": {
    "DefaultUsage": {
      "doc": "Demonstrates the intended normalized usage of Panel after adapter lowering.",
      "demonstrates": [
        "Normalized props for Panel.",
        "Adapter boundary expectations."
      ],
      "code": "<Panel\n  title=\"Today’s queue\"\n  density=\"compact\"\n  padding=\"none\"\n  footerActions={[assignAction]}\n  onFooterAction={handlePanelFooterAction}\n>\n  <ResourceTable {...tableProps} />\n</Panel>"
    }
  },
  "stories": {
    "Default": {
      "doc": "Tests the baseline Panel rendering with representative production-like data.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "default"
      },
      "asserts": [
        "Panel renders the Default scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "CompactNoPadding": {
      "doc": "Tests the CompactNoPadding scenario for Panel with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "compactNoPadding"
      },
      "asserts": [
        "Panel renders the CompactNoPadding scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "WithToolbarAction": {
      "doc": "Tests the WithToolbarAction scenario for Panel with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "withToolbarAction"
      },
      "asserts": [
        "Panel renders the WithToolbarAction scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "WithFooterActions": {
      "doc": "Tests footer action slot rendering for Panel.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "withFooterActions"
      },
      "asserts": [
        "Panel renders the WithFooterActions scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "BodyOnly": {
      "doc": "Tests the BodyOnly scenario for Panel with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "bodyOnly"
      },
      "asserts": [
        "Panel renders the BodyOnly scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "NestedResourceTable": {
      "doc": "Tests the NestedResourceTable scenario for Panel with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "nestedResourceTable"
      },
      "asserts": [
        "Panel renders the NestedResourceTable scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "MobilePanelPadding": {
      "doc": "Tests the MobilePanelPadding scenario for Panel with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "mobilePanelPadding"
      },
      "asserts": [
        "Panel renders the MobilePanelPadding scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    },
    {
      "id": "keep-raw-admin-dsl-json-parsing-in-adapters-not-in-this-widget",
      "severity": "recommended",
      "doc": "Keep raw Admin DSL JSON parsing in adapters, not in this widget."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"panel\" in renderAdminNode"
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;
