/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: Panel
 * Category: layout_widgets
 * Classification: {"level": "organism"}
 * Current source inventory: case "panel" in renderAdminNode
 *
 * Human notes from YAML:
 * {
 *   "intent": "Central admin surface primitive for dense workbench content. It owns header/body/footer chrome, padding, density, and action placement.",
 *   "adapter_boundary": "Adapter maps toolbarActions/footerActions and renders children separately; widget receives typed React children and action arrays.",
 *   "slot_intent": {
 *     "toolbarActions": "Toolbar actions are local to the panel header and usually secondary.",
 *     "footerActions": "Footer actions are local to the panel result/flow and should preserve panel context."
 *   },
 *   "storybook_intent": "Stories should cover no-padding table panels, toolbar actions, footer actions, body-only panels, and mobile padding."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "toolbarActions",
 *     "context": "panel",
 *     "callback_prop": "onToolbarAction",
 *     "intent": "Toolbar actions are local to the panel header and usually secondary.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   },
 *   {
 *     "name": "footerActions",
 *     "context": "panel",
 *     "callback_prop": "onFooterAction",
 *     "intent": "Footer actions are local to the panel result/flow and should preserve panel context.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Replace generated scaffold placeholder with final implementation.
 * - XXX: Keep raw Admin DSL JSON parsing in adapters, not in this widget.
 */
// XXX: Review this generated prop contract against the final widget implementation before relying on it as stable API.
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  PageActionHandler,
  PanelActionHandler,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

export interface PanelProps extends CommonWidgetProps {
  title?: string;
  subtitle?: string;
  eyebrow?: string;
  body?: string;
  padding?: "none" | "normal";
  toolbarActions?: ActionViewModel[];
  footerActions?: ActionViewModel[];
  children?: React.ReactNode;
  onToolbarAction?: PanelActionHandler;
  onFooterAction?: PanelActionHandler;
}
