/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/03-shell-widgets.yaml
 * Source YAML last commit: 8042b3e 2026-05-18T16:54:29-04:00 HAIR-041 Step 46: Specify widget IR YAML schema
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.shell.default
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type { Meta, StoryObj } from "@storybook/react";
import { DefaultAdminShell } from "./DefaultAdminShell";
import type { DefaultAdminShellProps } from "./DefaultAdminShell.types";

const defaultArgs = {
  pageId: "scaffold-default",
  shellKind: "admin",
  title: "Default Admin Shell",
  main: <div>Main content</div>,
} as unknown as DefaultAdminShellProps;

const meta = {
  title: "Admin DSL Widgets/Organisms/DefaultAdminShell",
  component: DefaultAdminShell,
  args: defaultArgs,
  parameters: {
    docs: {
      description: {
        component: "Render non-workbench Admin DSL pages with optional side surfaces. This keeps the legacy/default page shell separate from workbench chrome.",
      },
    },
  },
} satisfies Meta<typeof DefaultAdminShell>;

export default meta;
type Story = StoryObj<typeof meta>;

export const MainOnly: Story = {
  name: "MainOnly",
  parameters: { docs: { description: { story: "Tests the simplest fallback page shape with header chrome and one primary content column. It should remain useful for legacy admin pages and smoke fixtures." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <DefaultAdminShell {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "side": "absent"
}, asserts: [
  "Header title is visible.",
  "Main region renders without side-column spacing artifacts."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const WithSideSurfaces: Story = {
  name: "WithSideSurfaces",
  parameters: { docs: { description: { story: "Tests the optional side region used for drawers, modals, or detail panels. It should prove that side content aligns with the main region without requiring WorkbenchShell." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <DefaultAdminShell {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "side": "present"
}, asserts: [
  "Main and side regions form a two-column layout.",
  "Side region remains aligned with top of main content."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const CalendarShell: Story = {
  name: "CalendarShell",
  parameters: { docs: { description: { story: "Tests shell-level visual treatment for calendar pages, especially background and spacing differences inherited from the current default renderer." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <DefaultAdminShell {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "shellKind": "calendar"
}, asserts: [
  "Calendar shell background treatment is applied.",
  "Main content remains readable on calendar background."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const MobileSideColumn: Story = {
  name: "MobileSideColumn",
  parameters: { viewport: { defaultViewport: "iphone12" }, docs: { description: { story: "Tests responsive behavior when a side region exists. The side region should stack predictably and remain readable on narrow screens." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <DefaultAdminShell {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "side": "present"
}, asserts: [
  "Side region stacks after main content.",
  "No horizontal overflow is introduced."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
