/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/03-shell-widgets.yaml
 * Source YAML last commit: 8042b3e 2026-05-18T16:54:29-04:00 HAIR-041 Step 46: Specify widget IR YAML schema
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.shell.default
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

/**
 * Props for the fallback Admin DSL shell. This widget owns generic page chrome and optional side-surface layout for non-workbench shells while keeping page/node rendering outside the shell itself.
 */
export interface DefaultAdminShellProps {
  /**
   * Stable page identifier used for data attributes, screenshot naming, and shell-level trace context.
   */
  pageId: string;
  /**
   * The normalized Admin DSL shell kind. It should choose coarse page-level visual treatment only.
   */
  shellKind: "admin" | "dashboard" | "resource" | "calendar" | "settings" | "bare";
  /**
   * Optional small label above the title, commonly used for legacy Admin DSL pages or section context.
   */
  eyebrow?: string;
  /**
   * Main page title rendered by the shell chrome.
   */
  title: string;
  /**
   * Whether the shell should render its own title/description header. Adapters disable this when the page body already starts with a semantic PageHeader node.
   */
  showHeader?: boolean;
  /**
   * Optional page description under the title. Long descriptions should wrap without breaking side layout.
   */
  description?: string;
  /**
   * Already-rendered primary content region. The shell should not inspect or interpret the nodes that produced it.
   */
  main: React.ReactNode;
  /**
   * Optional already-rendered side content, typically drawers, modals, or detail panels shown as a side column in the non-workbench renderer.
   */
  side?: React.ReactNode;
}
