/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/03-shell-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: DefaultAdminShell
 * Category: shell_widgets
 * Classification: {"level": "organism", "role": "shell"}
 * Current source inventory: fallback branch in AdminPageRenderer in web/src/admin-dsl/render.tsx
 *
 * Purpose:
 * Render non-workbench Admin DSL pages with optional side surfaces. This keeps the legacy/default page shell separate from workbench chrome.
 *
 * Human notes from YAML:
 * {
 *   "intent": "Keeps the non-workbench shell path explicit while the workbench shell evolves. This prevents side-surface layout and page chrome from being hidden in AdminPageRenderer.",
 *   "adapter_boundary": "Adapter receives AdminPage and separates main region from side surfaces; widget receives already-rendered main/side React nodes.",
 *   "storybook_intent": "Stories should show main-only pages, side surfaces, calendar shell color, and mobile stacking."
 * }
 *
 * XXX items from YAML:
 * - XXX: Replace generated scaffold placeholder with final implementation.
 * - XXX: Keep raw Admin DSL JSON parsing in adapters, not in this widget.
 */
// XXX: Review this generated prop contract against the final widget implementation before relying on it as stable API.
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  PageActionHandler,
  PanelActionHandler,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

export interface DefaultAdminShellProps extends CommonWidgetProps {
  pageId: string;
  shellKind: "admin" | "dashboard" | "resource" | "calendar" | "settings" | "bare";
  eyebrow?: string;
  title: string;
  description?: string;
  main: React.ReactNode;
  side?: React.ReactNode;
}
