/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/03-shell-widgets.yaml
 * Source YAML last commit: 8042b3e 2026-05-18T16:54:29-04:00 HAIR-041 Step 46: Specify widget IR YAML schema
 * Target file previous commit: baf8866 2026-05-18T17:23:13-04:00 HAIR-041 Step 50: Regenerate widget scaffolds from schema v2
 * Widget ID: admin.shell.default
 *
 * This story file started as generated schema-v2 scaffold output. It now uses
 * purpose-built fixtures so DefaultAdminShell stories exercise distinct fallback
 * shell states instead of rendering the same default args repeatedly.
 */
import type { Meta, StoryObj } from "@storybook/react";
import { DefaultAdminShell } from "./DefaultAdminShell";
import type { DefaultAdminShellProps } from "./DefaultAdminShell.types";

function MainContent({ dense = false }: { dense?: boolean }) {
  return (
    <div style={{ display: "grid", gap: 14 }}>
      <section style={{ border: "1px solid #dfd2bd", borderRadius: 16, background: "#fffaf0", padding: 18 }}>
        <div style={{ fontSize: 11, letterSpacing: 1.1, textTransform: "uppercase", color: "#7b6c5d" }}>Primary region</div>
        <h2 style={{ margin: "8px 0 6px", fontSize: 24 }}>Rendered main Admin DSL content</h2>
        <p style={{ margin: 0, maxWidth: 640, color: "#6f6254" }}>
          The default shell receives this region after the renderer adapter has already interpreted Admin DSL nodes.
          It should only own page chrome and column layout.
        </p>
      </section>
      <div style={{ display: "grid", gridTemplateColumns: dense ? "repeat(3, minmax(0, 1fr))" : "repeat(2, minmax(0, 1fr))", gap: 12 }}>
        {["Services", "Availability", "Preview", "Audit", "Health", "Settings"].slice(0, dense ? 6 : 4).map((label, index) => (
          <article key={label} style={{ border: "1px solid #dfd2bd", borderRadius: 14, background: "#fffaf0", padding: 14 }}>
            <div style={{ fontSize: 11, letterSpacing: 1, textTransform: "uppercase", color: "#7b6c5d" }}>{label}</div>
            <strong style={{ display: "block", marginTop: 8, fontSize: 26 }}>{index + 1}</strong>
          </article>
        ))}
      </div>
    </div>
  );
}

function SideContent() {
  return (
    <div style={{ display: "grid", gap: 12 }}>
      <aside style={{ border: "1px solid #dfd2bd", borderRadius: 16, background: "#f8efde", padding: 16 }}>
        <div style={{ fontSize: 11, letterSpacing: 1.1, textTransform: "uppercase", color: "#7b6c5d" }}>Side surface</div>
        <h3 style={{ margin: "8px 0", fontSize: 20 }}>Draft drawer preview</h3>
        <p style={{ margin: 0, color: "#6f6254" }}>Optional side content aligns to the top of the main region on desktop.</p>
      </aside>
      <aside style={{ border: "1px solid #dfd2bd", borderRadius: 16, background: "#fffaf0", padding: 16 }}>
        <strong>Publish status</strong>
        <div style={{ marginTop: 8, color: "#6f6254" }}>No pending release.</div>
      </aside>
    </div>
  );
}

const defaultArgs = {
  pageId: "default-shell-story",
  shellKind: "admin",
  eyebrow: "Admin DSL",
  title: "Default Admin Shell",
  description: "Fallback page chrome for non-workbench Admin DSL screens.",
  main: <MainContent />,
} satisfies DefaultAdminShellProps;

const meta = {
  title: "Admin DSL Widgets/Organisms/DefaultAdminShell",
  component: DefaultAdminShell,
  args: defaultArgs,
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component:
          "Render non-workbench Admin DSL pages with optional side surfaces. This keeps the legacy/default page shell separate from workbench chrome.",
      },
    },
  },
} satisfies Meta<typeof DefaultAdminShell>;

export default meta;
type Story = StoryObj<typeof meta>;

export const MainOnly: Story = {
  name: "MainOnly",
  parameters: {
    docs: { description: { story: "Simplest fallback page shape with header chrome and one primary content column." } },
  },
};

export const WithSideSurfaces: Story = {
  name: "WithSideSurfaces",
  args: {
    ...defaultArgs,
    title: "Services & Draft Preview",
    main: <MainContent dense />,
    side: <SideContent />,
  },
  parameters: {
    docs: { description: { story: "Two-column fallback layout with already-rendered side surfaces." } },
  },
};

export const CalendarShell: Story = {
  name: "CalendarShell",
  args: {
    ...defaultArgs,
    shellKind: "calendar",
    eyebrow: "Calendar",
    title: "June Availability",
    description: "Calendar shell variant uses the calendar page background while preserving readable page chrome.",
    main: <MainContent dense />,
  },
  parameters: {
    docs: { description: { story: "Calendar-flavored fallback shell background and spacing." } },
  },
};

export const MobileSideColumn: Story = {
  name: "MobileSideColumn",
  args: {
    ...defaultArgs,
    title: "Mobile Side Stack",
    main: <MainContent />,
    side: <SideContent />,
  },
  parameters: {
    viewport: { defaultViewport: "iphone12" },
    docs: { description: { story: "Narrow viewport where optional side content stacks after the main region without horizontal overflow." } },
  },
};
