/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/03-shell-widgets.yaml
 * Source YAML last commit: 8042b3e 2026-05-18T16:54:29-04:00 HAIR-041 Step 46: Specify widget IR YAML schema
 * Target file previous commit: baf8866 2026-05-18T17:23:13-04:00 HAIR-041 Step 50: Regenerate widget scaffolds from schema v2
 * Widget ID: admin.shell.default
 *
 * This file started as generated schema-v2 scaffold output. The visual shell
 * implementation below was extracted from the AdminPageRenderer fallback branch
 * in web/src/admin-dsl/render.tsx so the renderer can become an adapter instead
 * of owning default page-frame HTML.
 */
import { defaultAdminShellWidgetMetadata } from "./DefaultAdminShell.metadata";
import type { DefaultAdminShellProps } from "./DefaultAdminShell.types";
import { color, type } from "../../../../fringe-ui/tokens";
import { adminPageRootStyle, adminShellGridStyle, widgetDataAttributes } from "../../shared";

const defaultAdminShellCss = `
  .adminDslDefaultRoot { box-sizing: border-box; }
  .adminDslDefaultRoot *, .adminDslDefaultRoot *::before, .adminDslDefaultRoot *::after { box-sizing: border-box; }
  .adminDslDefaultGrid { grid-template-columns: var(--admin-dsl-grid-columns, 1fr); }
  .adminDslDefaultTitle { text-wrap: balance; overflow-wrap: anywhere; }
  .adminDslDefaultSideColumn { min-width: 0; }
  @media (max-width: 720px) {
    .adminDslDefaultRoot { padding: 16px !important; overflow-x: hidden !important; }
    .adminDslDefaultGrid { grid-template-columns: 1fr !important; gap: 16px !important; }
    .adminDslDefaultTitle { font-size: clamp(28px, 9vw, 34px) !important; line-height: 0.98 !important; letter-spacing: -0.15px !important; }
    .adminDslDefaultSideColumn { display: grid !important; grid-template-columns: 1fr !important; margin: 16px 0 22px !important; }
  }
  @media (max-width: 430px) {
    .adminDslDefaultRoot { padding: 12px !important; }
  }
`;

export function DefaultAdminShell({
  pageId,
  shellKind,
  eyebrow = "Admin DSL",
  title,
  description,
  main,
  side,
}: DefaultAdminShellProps) {
  const hasSide = Boolean(side);

  return (
    <main
      className="adminDslRoot adminDslDefaultRoot"
      style={{ ...adminPageRootStyle({ shellKind }), padding: 24 }}
      data-admin-dsl-page={pageId}
      data-admin-dsl-shell={shellKind}
      {...widgetDataAttributes(defaultAdminShellWidgetMetadata.widgetId)}
    >
      <style>{defaultAdminShellCss}</style>
      <div
        className="adminDslGrid adminDslDefaultGrid"
        style={adminShellGridStyle({ hasSide })}
      >
        <section style={{ minWidth: 0 }} aria-labelledby={`${pageId}-title`}>
          <header style={{ marginBottom: 24 }}>
            {eyebrow ? <div style={{ ...type.eyebrow, color: color.plum }}>{eyebrow}</div> : null}
            <h1
              id={`${pageId}-title`}
              className="adminDslTitle adminDslDefaultTitle"
              style={{ ...type.display2, fontSize: 56, margin: "6px 0 8px" }}
            >
              {title}
            </h1>
            {description ? <p style={{ ...type.bodyLg, color: color.softInk, maxWidth: 680, margin: 0 }}>{description}</p> : null}
          </header>
          <div style={{ display: "grid", gap: 4 }}>{main}</div>
        </section>
        {hasSide ? (
          <aside
            className="adminDslSideColumn adminDslDefaultSideColumn"
            aria-label="Supplementary admin surfaces"
            style={{ display: "grid", gap: 14, alignContent: "start" }}
          >
            {side}
          </aside>
        ) : null}
      </div>
    </main>
  );
}
