/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/03-shell-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: DefaultAdminShell
 * Category: shell_widgets
 * Classification: {"level": "organism", "role": "shell"}
 * Current source inventory: fallback branch in AdminPageRenderer in web/src/admin-dsl/render.tsx
 *
 * Purpose:
 * Render non-workbench Admin DSL pages with optional side surfaces. This keeps the legacy/default page shell separate from workbench chrome.
 *
 * Human notes from YAML:
 * {
 *   "intent": "Keeps the non-workbench shell path explicit while the workbench shell evolves. This prevents side-surface layout and page chrome from being hidden in AdminPageRenderer.",
 *   "adapter_boundary": "Adapter receives AdminPage and separates main region from side surfaces; widget receives already-rendered main/side React nodes.",
 *   "storybook_intent": "Stories should show main-only pages, side surfaces, calendar shell color, and mobile stacking."
 * }
 *
 * XXX items from YAML:
 * - XXX: Replace generated scaffold placeholder with final implementation.
 * - XXX: Keep raw Admin DSL JSON parsing in adapters, not in this widget.
 */
import type * as React from "react";
import type { ReactNode } from "react";
import type { DefaultAdminShellProps } from "./DefaultAdminShell.types";

const widgetClassification = "{\"level\": \"organism\", \"role\": \"shell\"}";
const widgetPurpose = "Render non-workbench Admin DSL pages with optional side surfaces. This keeps the legacy/default page shell separate from workbench chrome.";
const widgetHumanNotes = "{\n  \"intent\": \"Keeps the non-workbench shell path explicit while the workbench shell evolves. This prevents side-surface layout and page chrome from being hidden in AdminPageRenderer.\",\n  \"adapter_boundary\": \"Adapter receives AdminPage and separates main region from side surfaces; widget receives already-rendered main/side React nodes.\",\n  \"storybook_intent\": \"Stories should show main-only pages, side surfaces, calendar shell color, and mobile stacking.\"\n}";
const widgetActionSlots = "No action slots declared in YAML.";
const widgetXxx = "XXX: Replace generated scaffold placeholder with final implementation.\nXXX: Keep raw Admin DSL JSON parsing in adapters, not in this widget.";

/**
 * Scaffold for `DefaultAdminShell`.
 *
 * Generated from `/home/manuel/workspaces/2026-04-21/hair-v2/hair-booking/ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/03-shell-widgets.yaml`.
 * Current source inventory: fallback branch in AdminPageRenderer in web/src/admin-dsl/render.tsx.
 *
 * XXX: Replace this placeholder body with the real visual implementation. Keep
 * raw Admin DSL node decoding in renderer adapters; this component should
 * receive typed widget props only.
 */
export function DefaultAdminShell(props: DefaultAdminShellProps) {
  const scaffoldProps = props as DefaultAdminShellProps & {
    id?: string;
    className?: string;
    style?: React.CSSProperties;
    children?: ReactNode;
    title?: string;
    label?: string;
    name?: string;
    value?: unknown;
  };
  const heading = scaffoldProps.title || scaffoldProps.label || scaffoldProps.name || "DefaultAdminShell";

  return (
    <section
      id={scaffoldProps.id}
      className={scaffoldProps.className}
      data-admin-dsl-widget="DefaultAdminShell"
      data-admin-dsl-widget-level="organism"
      style={scaffoldProps.style}
    >
      <div style={{ border: "1px dashed #c8b89b", borderRadius: 12, padding: 12, background: "#fffaf0" }}>
        <strong>{heading}</strong>
        <div style={{ marginTop: 4, fontSize: 12, color: "#6f6254" }}>
          DefaultAdminShell scaffold — XXX replace with final implementation.
        </div>
        <dl style={{ margin: "10px 0 0", display: "grid", gap: 6, fontSize: 12, color: "#6f6254" }}>
          <div><dt style={{ fontWeight: 700 }}>Classification</dt><dd style={{ margin: 0, whiteSpace: "pre-wrap" }}>{widgetClassification}</dd></div>
          <div><dt style={{ fontWeight: 700 }}>Purpose</dt><dd style={{ margin: 0, whiteSpace: "pre-wrap" }}>{widgetPurpose}</dd></div>
          <div><dt style={{ fontWeight: 700 }}>Human notes</dt><dd style={{ margin: 0, whiteSpace: "pre-wrap" }}>{widgetHumanNotes}</dd></div>
          <div><dt style={{ fontWeight: 700 }}>Action slots</dt><dd style={{ margin: 0, whiteSpace: "pre-wrap" }}>{widgetActionSlots}</dd></div>
          <div><dt style={{ fontWeight: 700 }}>Implementation warnings</dt><dd style={{ margin: 0, whiteSpace: "pre-wrap" }}>{widgetXxx}</dd></div>
        </dl>
      </div>
      {scaffoldProps.children ? <div style={{ marginTop: 12 }}>{scaffoldProps.children}</div> : null}
    </section>
  );
}
