/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/10-form-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.form.admin-form
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

/**
 * Props for AdminForm. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface AdminFormProps<Values = Record<string, unknown>> extends CommonWidgetProps {
  /**
   * formId configures admin form. Type: string.
   */
  formId: string;
  /**
   * Primary heading or title rendered by AdminForm.
   */
  title?: string;
  /**
   * Whether AdminForm should show unsaved-change state.
   */
  dirty?: boolean;
  /**
   * Whether AdminForm should show in-progress state.
   */
  pending?: boolean;
  /**
   * Lifecycle state rendered by AdminForm.
   */
  state?: "idle" | "dirty" | "pending" | "success" | "error";
  /**
   * Validation errors rendered by AdminForm.
   */
  errors?: Record<string, string>;
  /**
   * Ordered action list for the AdminForm slot. Presentation should be derived from semantic slot and action intent.
   */
  actions?: ActionViewModel[];
  /**
   * Already-rendered child content owned by the caller/adapter and placed inside AdminForm.
   */
  children: React.ReactNode;
  /**
   * onFormAction configures admin form. Type: FormActionHandler<Values>.
   */
  onFormAction?: FormActionHandler<Values>;
}
