/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: ResourceTableCell
 * Category: resource_widgets
 * Classification: {"level": "molecule"}
 * Current source inventory: renderTableCell
 *
 * Human notes from YAML:
 * {
 *   "intent": "Localizes cell-kind rendering so ResourceTable is not a pile of conditional JSX. It can later become a registry of cell renderers.",
 *   "adapter_boundary": "Receives already-normalized column and row data; should not parse AdminNode directly.",
 *   "slot_intent": {
 *     "rowAction": "Only action/overflow cells invoke row-scoped callbacks; text/badge/boolean cells are pure display."
 *   },
 *   "storybook_intent": "Stories should cover every current cell kind and make unmapped kinds obvious."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "rowAction",
 *     "context": "table row when column kind is actions/overflowActions",
 *     "callback_prop": "onRowAction",
 *     "intent": "Only action/overflow cells invoke row-scoped callbacks; text/badge/boolean cells are pure display.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Implement real cell-kind rendering or a cell renderer registry.
 */
// XXX: Review this generated prop contract against the final widget implementation before relying on it as stable API.
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  PageActionHandler,
  PanelActionHandler,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../../../shared/types";
import type { ResourceTableColumn } from "../../ResourceTable.types";

export interface ResourceTableCellProps<Row = Record<string, unknown>> {
  column: ResourceTableColumn<Row>;
  row: Row;
  tableId: string;
  onRowAction?: TableRowActionHandler<Row>;
}
