/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T00:32:13+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: baf8866 2026-05-18T17:21:36-04:00 HAIR-041 Step 50: Regenerate widget scaffolds from schema v2
 * Widget ID: admin.resource.resource-table-cell
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../../../shared/types";
import type { ResourceTableColumn } from "../../ResourceTable.types";

/**
 * Props for ResourceTableCell. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface ResourceTableCellProps<Row = Record<string, unknown>> {
  /**
   * column configures resource table cell. Type: ResourceTableColumn<Row>.
   */
  column: ResourceTableColumn<Row>;
  /**
   * row configures resource table cell. Type: Row.
   */
  row: Row;
  /**
   * Stable table id used by ResourceTableCell for selection state, action context, and test hooks.
   */
  tableId: string;
  /**
   * Callback invoked by ResourceTableCell with table id, row, and optional row id.
   */
  onRowAction?: TableRowActionHandler<Row>;
}
