/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T00:23:55+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: baf8866 2026-05-18T17:21:36-04:00 HAIR-041 Step 50: Regenerate widget scaffolds from schema v2
 * Widget ID: admin.layout.dashboard-grid
 *
 * Manual edits after generation:
 * - 2026-05-18 / HAIR-041 Step 76: Promoted scaffold to real responsive grid and item components extracted from render.tsx.
 * - 2026-05-18 / HAIR-041 Step 76: Added generated design-language data attributes and local responsive CSS.
 *
 * Keep raw Admin DSL JSON decoding in adapters; this widget receives typed props only.
 */
import { dataAttrsFromRecord, widgetDataAttributes } from "../../shared";
import { dashboardGridWidgetMetadata } from "./DashboardGrid.metadata";
import type { DashboardGridItemProps, DashboardGridProps } from "./DashboardGrid.types";

const dashboardGridCss = `
  @media (max-width: 980px) {
    .adminDslDashboardGrid { grid-template-columns: repeat(var(--admin-dsl-dashboard-grid-tablet-columns, 8), minmax(0, 1fr)) !important; }
    .adminDslDashboardGridItem { grid-column: span min(var(--admin-dsl-dashboard-grid-tablet-span, var(--admin-dsl-dashboard-grid-desktop-span, 8)), var(--admin-dsl-dashboard-grid-tablet-columns, 8)) !important; }
  }
  @media (max-width: 720px) {
    .adminDslDashboardGrid { grid-template-columns: repeat(var(--admin-dsl-dashboard-grid-mobile-columns, 1), minmax(0, 1fr)) !important; gap: var(--admin-dsl-dashboard-grid-mobile-gap, 16px) !important; }
    .adminDslDashboardGridItem { grid-column: span min(var(--admin-dsl-dashboard-grid-mobile-span, 1), var(--admin-dsl-dashboard-grid-mobile-columns, 1)) !important; }
  }
`;

function clampColumn(value: unknown, fallback: number) {
  const numeric = Number(value || fallback);
  return Number.isFinite(numeric) && numeric > 0 ? Math.max(1, Math.min(24, Math.round(numeric))) : fallback;
}

function gapValue(gap: DashboardGridProps["gap"]) {
  if (gap === "compact") return 16;
  if (gap === "spacious") return 28;
  return 20;
}

export function DashboardGrid({ id, className, style, dataAttributes, columns, gap = "normal", children }: DashboardGridProps) {
  const desktopColumns = clampColumn(columns?.desktop, 12);
  const tabletColumns = clampColumn(columns?.tablet, Math.min(desktopColumns, 8));
  const mobileColumns = clampColumn(columns?.mobile, 1);
  const gapPx = gapValue(gap);
  const dataAttrs = dataAttrsFromRecord(dataAttributes);

  return (
    <div
      id={id}
      className={["adminDslDashboardGrid", className].filter(Boolean).join(" ") || undefined}
      style={{
        display: "grid",
        gridTemplateColumns: `repeat(${desktopColumns}, minmax(0, 1fr))`,
        gap: gapPx,
        alignItems: "start",
        ["--admin-dsl-dashboard-grid-tablet-columns" as string]: tabletColumns,
        ["--admin-dsl-dashboard-grid-mobile-columns" as string]: mobileColumns,
        ["--admin-dsl-dashboard-grid-mobile-gap" as string]: `${Math.min(gapPx, 16)}px`,
        ...style,
      }}
      {...widgetDataAttributes(dashboardGridWidgetMetadata.widgetId, dashboardGridWidgetMetadata.classification.level)}
      {...dataAttrs}
    >
      <style>{dashboardGridCss}</style>
      {children}
    </div>
  );
}

export function DashboardGridItem({ span, order, children }: DashboardGridItemProps) {
  const desktopSpan = clampColumn(span?.desktop, 12);
  const tabletSpan = clampColumn(span?.tablet ?? span?.desktop, Math.min(desktopSpan, 8));
  const mobileSpan = clampColumn(span?.mobile, 1);

  return (
    <div
      className="adminDslDashboardGridItem"
      style={{
        minWidth: 0,
        gridColumn: `span ${desktopSpan}`,
        order,
        ["--admin-dsl-dashboard-grid-desktop-span" as string]: desktopSpan,
        ["--admin-dsl-dashboard-grid-tablet-span" as string]: tabletSpan,
        ["--admin-dsl-dashboard-grid-mobile-span" as string]: mobileSpan,
      }}
    >
      {children}
    </div>
  );
}
