/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: SearchBox
 * Category: layout_widgets
 * Classification: {"level": "molecule"}
 * Current source inventory: case "searchBox"
 *
 * Human notes from YAML:
 * {
 *   "intent": "Owns search form semantics and submit behavior in a reusable molecule.",
 *   "adapter_boundary": "Adapter maps placeholder/value/action; widget emits query text through onSearch.",
 *   "slot_intent": {
 *     "searchSubmit": "Search submit actions receive query context, not raw form events."
 *   },
 *   "storybook_intent": "Stories should cover default, initial value, no action, and dispatch payload."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "searchSubmit",
 *     "callback_prop": "onSearch",
 *     "intent": "Search submit actions receive query context, not raw form events.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Replace generated scaffold placeholder with final implementation.
 * - XXX: Keep raw Admin DSL JSON parsing in adapters, not in this widget.
 */
// XXX: Replace generated defaultArgs with purposeful fixtures for every planned story before treating this as visual coverage.
import type { Meta, StoryObj } from "@storybook/react";
import { SearchBox } from "./SearchBox";
import type { SearchBoxProps } from "./SearchBox.types";

const defaultArgs = {
  placeholder: "Search requests",
  value: "",
} as unknown as SearchBoxProps;

const meta = {
  title: "Admin DSL Widgets/Molecules/SearchBox",
  component: SearchBox,
  args: defaultArgs,
} satisfies Meta<typeof SearchBox>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const WithInitialValue: Story = {};
export const NoAction: Story = {};
export const SubmitDispatch: Story = {};
