/**
 * GENERATED DESIGN LANGUAGE — REVIEW BEFORE HAND EDITING.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/06-generate-admin-dsl-design-language.py
 * Generated at: 2026-05-18T23:28:32+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/15-design-language.yaml
 * Source YAML last commit: 9a1f847 2026-05-18T19:02:44-04:00 HAIR-041 Step 66: Add design language IR generator
 * Target file previous commit: 9a1f847 2026-05-18T19:02:44-04:00 HAIR-041 Step 66: Add design language IR generator
 *
 * This file is generated from Admin DSL Design Language IR. Update the YAML and
 * regenerate rather than editing this file directly unless explicitly promoting
 * it to hand-written code.
 */
import type { CSSProperties } from "react";
import { color, font, radius, shadow } from "../../../fringe-ui/tokens";
import type { ActionViewModel, AdminActionPlacement, AdminActionSize, AdminActionVariant } from "./types";

export const actionPlacementDefaults = {
  pageHeader: { defaultVariant: "soft", defaultSize: "md" },
  toolbar: { defaultVariant: "soft", defaultSize: "md" },
  panelToolbar: { defaultVariant: "soft", defaultSize: "sm" },
  panelFooter: { defaultVariant: "subtle", defaultSize: "sm" },
  formFooter: { defaultVariant: "formPrimary", defaultSize: "sm" },
  row: { defaultVariant: "subtle", defaultSize: "sm" },
  rowOverflow: { defaultVariant: "overflow", defaultSize: "sm" },
  bulkToolbar: { defaultVariant: "soft", defaultSize: "touch" },
  calendarCell: { defaultVariant: "soft", defaultSize: "sm" },
  sidebarNav: { defaultVariant: "subtle", defaultSize: "touch" },
  footer: { defaultVariant: "subtle", defaultSize: "sm" },
  detail: { defaultVariant: "subtle", defaultSize: "sm" },
  overflow: { defaultVariant: "overflow", defaultSize: "sm" },
} as const satisfies Record<string, { defaultVariant: AdminActionVariant; defaultSize: AdminActionSize }>;

export function actionPlacement(action: ActionViewModel, fallback: AdminActionPlacement = "toolbar"): AdminActionPlacement {
  return ((typeof action.placement === "string" && action.placement) || fallback) as AdminActionPlacement;
}

export function inferActionVariant(action: ActionViewModel, explicit?: AdminActionVariant, fallbackPlacement: AdminActionPlacement = "toolbar"): AdminActionVariant {
  if (explicit) return explicit;
  if (action.intent === "danger") return "danger";
  if (action.priority === "primary" || action.intent === "primary") {
    return actionPlacement(action, fallbackPlacement) === "formFooter" ? "formPrimary" : "solid";
  }
  if (action.presentation === "overflow" || actionPlacement(action, fallbackPlacement) === "rowOverflow") return "overflow";
  const placement = actionPlacement(action, fallbackPlacement);
  return actionPlacementDefaults[placement]?.defaultVariant ?? "soft";
}

export function inferActionSize(action: ActionViewModel, explicit?: AdminActionSize, fallbackPlacement: AdminActionPlacement = "toolbar"): AdminActionSize {
  if (explicit) return explicit;
  const placement = actionPlacement(action, fallbackPlacement);
  return actionPlacementDefaults[placement]?.defaultSize ?? "md";
}

export function actionButtonStyle(options: {
  variant: AdminActionVariant;
  size: AdminActionSize;
  disabled?: boolean;
  loading?: boolean;
}): CSSProperties {
  const { variant, size, disabled, loading } = options;
  const subtle = variant === "subtle" || variant === "overflow";
  const solid = variant === "solid";
  const danger = variant === "danger";
  const formPrimary = variant === "formPrimary";
  const minHeight = variant === "overflow" ? 32 : size === "touch" ? 44 : subtle ? 32 : size === "sm" ? 34 : 38;
  const padding = variant === "overflow" ? "6px 8px" : subtle ? "6px 8px" : size === "touch" ? "9px 14px" : size === "sm" ? "7px 10px" : "8px 12px";

  return {
    minHeight,
    minWidth: variant === "overflow" ? 32 : undefined,
    border: subtle ? "1px solid transparent" : `1px solid ${danger ? color.danger : solid ? color.ink : color.rule}`,
    background: disabled ? color.ruleSoft : subtle ? "transparent" : solid ? color.ink : formPrimary ? color.cream : color.paper,
    color: disabled ? color.soft : solid ? color.paper : danger ? color.danger : subtle ? color.plum : color.ink,
    borderRadius: radius.md,
    padding,
    fontFamily: subtle ? font.sans : font.mono,
    fontSize: subtle ? 13 : 11,
    letterSpacing: subtle ? 0 : 0.6,
    textTransform: subtle ? "none" : "uppercase",
    cursor: disabled || loading ? "not-allowed" : "pointer",
    opacity: loading ? 0.72 : 1,
    boxShadow: solid ? shadow.sm : "none",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    lineHeight: 1.15,
    fontWeight: subtle ? 500 : 700,
  };
}

export function sidebarNavButtonStyle(options: { active?: boolean; disabled?: boolean }): CSSProperties {
  const { active, disabled } = options;
  return {
    minHeight: 38,
    border: "none",
    borderRadius: radius.md,
    background: active ? "rgba(18, 17, 16, 0.07)" : "transparent",
    color: disabled ? color.soft : color.ink,
    display: "grid",
    gridTemplateColumns: "22px 1fr",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    textAlign: "left",
    cursor: disabled ? "default" : "pointer",
    fontFamily: font.sans,
    fontSize: 12,
    lineHeight: 1.4,
    fontWeight: active ? 800 : 500,
  };
}

export function shellMenuButtonStyle(): CSSProperties {
  return {
    ...actionButtonStyle({ variant: "soft", size: "sm" }),
    minHeight: 34,
  };
}
