/**
 * GENERATED DESIGN LANGUAGE — REVIEW BEFORE HAND EDITING.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/06-generate-admin-dsl-design-language.py
 * Generated at: 2026-05-18T23:02:22+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/15-design-language.yaml
 * Source YAML last commit: none (untracked or no history)
 * Target file previous commit: none (untracked or no history)
 *
 * This file is generated from Admin DSL Design Language IR. Update the YAML and
 * regenerate rather than editing this file directly unless explicitly promoting
 * it to hand-written code.
 */
import type { ActionViewModel } from "./types";

export function dataAttrsFromRecord(values?: Record<string, string | number | boolean | undefined>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(values ?? {})
      .filter(([, value]) => value !== undefined)
      .map(([key, value]) => [`data-${key}`, String(value)]),
  ) as Record<string, string>;
}

export function widgetDataAttributes(widgetId: string, level?: string): Record<string, string> {
  return {
    "data-admin-dsl-widget-id": widgetId,
    ...(level ? { "data-admin-dsl-widget-level": level } : {}),
  };
}

export function actionDataAttributes(action: ActionViewModel): Record<string, string | undefined> {
  return {
    "data-admin-dsl-action-intent": typeof action.intent === "string" ? action.intent : undefined,
    "data-admin-dsl-action-priority": typeof action.priority === "string" ? action.priority : undefined,
    "data-admin-dsl-action-placement": typeof action.placement === "string" ? action.placement : undefined,
    "data-admin-dsl-action-confirm": action.requiresConfirmation ? "true" : undefined,
  };
}
