/**
 * GENERATED DESIGN LANGUAGE — REVIEW BEFORE HAND EDITING.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/06-generate-admin-dsl-design-language.py
 * Generated at: 2026-05-19T02:13:17+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/15-design-language.yaml
 * Source YAML last commit: bf0d99a 2026-05-18T21:42:24-04:00 HAIR-041 Step 93: Add widget playbook compliance audit guide
 * Target file previous commit: 9c24194 2026-05-18T21:14:43-04:00 HAIR-041 Step 86: Generate selection and badge style helpers
 *
 * This file is generated from Admin DSL Design Language IR. Update the YAML and
 * regenerate rather than editing this file directly unless explicitly promoting
 * it to hand-written code.
 */
export type * from "./types";
export * from "./designTokens";
export * from "./actionStyles";
export * from "./layoutStyles";
export * from "./typography";
export * from "./dataAttributes";
