/**
 * GENERATED DESIGN LANGUAGE — REVIEW BEFORE HAND EDITING.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/06-generate-admin-dsl-design-language.py
 * Generated at: 2026-05-19T01:14:12+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/15-design-language.yaml
 * Source YAML last commit: 9a1f847 2026-05-18T19:02:44-04:00 HAIR-041 Step 66: Add design language IR generator
 * Target file previous commit: e86bd14 2026-05-18T19:28:59-04:00 HAIR-041 Step 69: Refresh PageHeader scaffold
 *
 * This file is generated from Admin DSL Design Language IR. Update the YAML and
 * regenerate rather than editing this file directly unless explicitly promoting
 * it to hand-written code.
 */
export type * from "./types";
export * from "./designTokens";
export * from "./actionStyles";
export * from "./layoutStyles";
export * from "./typography";
export * from "./dataAttributes";
