/**
 * GENERATED DESIGN LANGUAGE — REVIEW BEFORE HAND EDITING.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/06-generate-admin-dsl-design-language.py
 * Generated at: 2026-05-18T23:28:32+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/15-design-language.yaml
 * Source YAML last commit: 9a1f847 2026-05-18T19:02:44-04:00 HAIR-041 Step 66: Add design language IR generator
 * Target file previous commit: 9a1f847 2026-05-18T19:02:44-04:00 HAIR-041 Step 66: Add design language IR generator
 *
 * This file is generated from Admin DSL Design Language IR. Update the YAML and
 * regenerate rather than editing this file directly unless explicitly promoting
 * it to hand-written code.
 */
import type { CSSProperties } from "react";
import { color, font, radius, shadow } from "../../../fringe-ui/tokens";

export const adminSurfaceStyle: CSSProperties = {
  background: color.paper,
  border: `1px solid ${color.rule}`,
  borderRadius: radius.lg,
  boxShadow: shadow.sm,
};

export function adminPageRootStyle(options: { shellKind?: string } = {}): CSSProperties {
  return {
    minHeight: "100vh",
    background: options.shellKind === "calendar" ? color.cream : color.creamDeep,
    color: color.ink,
    fontFamily: font.sans,
  };
}

export function adminActionRowStyle(options: { gap?: number; justifyContent?: CSSProperties["justifyContent"] } = {}): CSSProperties {
  return {
    display: "flex",
    gap: options.gap ?? 8,
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: options.justifyContent ?? "flex-start",
  };
}

export function adminShellGridStyle(options: { hasSide?: boolean; maxWidth?: number | string } = {}): CSSProperties {
  return {
    maxWidth: options.maxWidth ?? 1180,
    margin: "0 auto",
    display: "grid",
    ["--admin-dsl-grid-columns" as string]: options.hasSide ? "minmax(0, 1fr) 340px" : "1fr",
    gap: 20,
  };
}
