/**
 * GENERATED DESIGN LANGUAGE — REVIEW BEFORE HAND EDITING.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/06-generate-admin-dsl-design-language.py
 * Generated at: 2026-05-19T02:13:17+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/15-design-language.yaml
 * Source YAML last commit: bf0d99a 2026-05-18T21:42:24-04:00 HAIR-041 Step 93: Add widget playbook compliance audit guide
 * Target file previous commit: 9c24194 2026-05-18T21:14:43-04:00 HAIR-041 Step 86: Generate selection and badge style helpers
 *
 * This file is generated from Admin DSL Design Language IR. Update the YAML and
 * regenerate rather than editing this file directly unless explicitly promoting
 * it to hand-written code.
 */
import type { CSSProperties, ReactNode } from "react";

export type AdminActionPlacement = "bulkToolbar" | "calendarCell" | "detail" | "footer" | "formFooter" | "overflow" | "pageHeader" | "panelFooter" | "panelToolbar" | "row" | "rowOverflow" | "sidebarNav" | "toolbar";
export type AdminActionVariant = "danger" | "formPrimary" | "overflow" | "soft" | "solid" | "subtle";
export type AdminActionSize = "md" | "overflow" | "sm" | "subtle" | "touch";
export type AdminTypographyRole = "actionLabel" | "body" | "bodyLarge" | "bodyMuted" | "eyebrow" | "navLabel" | "pageTitle" | "panelTitle" | "productMark" | "subtleActionLabel";
export type AdminTone = "neutral" | "success" | "warning" | "danger" | "info" | "muted" | string;

export interface ActionViewModel {
  id?: string;
  type: "open" | "close" | "navigate" | "mutation" | "confirm" | "refresh" | "upload" | string;
  target: string;
  label: string;
  intent?: "neutral" | "primary" | "danger" | string;
  priority?: "primary" | "secondary" | "tertiary" | string;
  presentation?: "button" | "icon" | "menuItem" | "overflow" | "link" | string;
  placement?: AdminActionPlacement | string;
  disabled?: boolean;
  loading?: boolean;
  accessibilityLabel?: string;
  requiresConfirmation?: boolean;
  confirmation?: {
    title?: string;
    body?: string;
    confirmLabel?: string;
    cancelLabel?: string;
  };
  [key: string]: unknown;
}

export interface SidebarNavItem {
  id: string;
  label: string;
  icon?: string;
  action?: ActionViewModel;
  [key: string]: unknown;
}

export interface SidebarNavProps {
  activeItemId?: string;
  items: SidebarNavItem[];
}

export interface CommonWidgetProps {
  id?: string;
  className?: string;
  style?: CSSProperties;
  density?: "compact" | "normal" | "spacious";
  tone?: AdminTone;
  dataAttributes?: Record<string, string | number | boolean | undefined>;
}

export type ResourceTableColumnKind =
  | "text"
  | "badge"
  | "status"
  | "actions"
  | "image"
  | "date"
  | "number"
  | "boolean"
  | "dragHandle"
  | string;

export type OverlaySurfaceKind = "modal" | "drawer" | "popover" | "sheet" | string;

export interface PaginationModel {
  page: number;
  total: number;
  actions?: ActionViewModel[];
}

export type PageActionHandler = (action: ActionViewModel, context: { pageId?: string }) => void;
export type PanelActionHandler = (action: ActionViewModel, context: { panelId?: string }) => void;
export type TableRowActionHandler<Row> = (action: ActionViewModel, context: { tableId: string; row: Row; rowId?: string }) => void;
export type TableBulkActionHandler<Row> = (action: ActionViewModel, context: { tableId: string; scope: "visible" | "selected" | "allMatching"; rows: Row[]; selectedRowIds: string[] }) => void;
export type FormActionHandler<Values> = (action: ActionViewModel, context: { formId: string; values: Values }) => void;
export type CalendarCellActionHandler = (action: ActionViewModel, context: { calendarId: string; date: string }) => void;

export interface GeneratedStoryFixture {
  scenario: string;
  [key: string]: unknown;
}

export interface WidgetScaffoldDiagnostics {
  widgetId: string;
  purpose: string;
  adapterBoundary?: string;
  implementationNotes: string[];
  accessibilityNotes: string[];
  actionSlots: Record<string, unknown>;
  examples: Record<string, unknown>;
}

export type WidgetChildren = ReactNode;
