/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T00:32:12+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.layout.toolbar
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for Toolbar.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const toolbarWidgetMetadata = {
  "widgetId": "admin.layout.toolbar",
  "name": "Toolbar",
  "category": "layout_widgets",
  "classification": {
    "level": "molecule",
    "description": "Toolbar participates in the Admin DSL component system as a molecule; its level controls scaffold location and Storybook grouping."
  },
  "purpose": "Small page/tool action row for legacy or non-workbench pages. It should eventually be a thin ActionGroup wrapper.",
  "designRationale": "Small page/tool action row for legacy or non-workbench pages. It should eventually be a thin ActionGroup wrapper.",
  "adapterBoundary": "Adapter maps toolbar node actions into ActionViewModel list.",
  "implementationNotes": [
    "Implement Toolbar using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure Toolbar exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "toolbarActions": {
      "doc": "General toolbar actions receive page/tool context, not row or form context.",
      "callback": "onToolbarAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "ToolbaractionsContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the toolbarActions slot on Toolbar."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by Toolbar. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed Toolbar props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<Toolbar />"
    }
  },
  "stories": {
    "Default": {
      "doc": "Tests the baseline Toolbar rendering with representative production-like data.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "default"
      },
      "asserts": [
        "Toolbar renders the Default scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "ManyActionsWrap": {
      "doc": "Tests the ManyActionsWrap scenario for Toolbar with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "manyActionsWrap"
      },
      "asserts": [
        "Toolbar renders the ManyActionsWrap scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "MobileTouchTargets": {
      "doc": "Tests the MobileTouchTargets scenario for Toolbar with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "mobileTouchTargets"
      },
      "asserts": [
        "Toolbar renders the MobileTouchTargets scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    },
    {
      "id": "keep-raw-admin-dsl-json-parsing-in-adapters-not-in-this-widget",
      "severity": "recommended",
      "doc": "Keep raw Admin DSL JSON parsing in adapters, not in this widget."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"toolbar\""
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;
