/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.layout.toolbar
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type { ReactNode } from "react";
import type { ToolbarProps } from "./Toolbar.types";

const diagnostics = {
  "widgetId": "admin.layout.toolbar",
  "purpose": "Small page/tool action row for legacy or non-workbench pages. It should eventually be a thin ActionGroup wrapper.",
  "adapterBoundary": "Adapter maps toolbar node actions into ActionViewModel list.",
  "implementationNotes": [
    "Implement Toolbar using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure Toolbar exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "toolbarActions": {
      "doc": "General toolbar actions receive page/tool context, not row or form context.",
      "callback": "onToolbarAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "ToolbaractionsContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the toolbarActions slot on Toolbar."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by Toolbar. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed Toolbar props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<Toolbar />"
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    },
    {
      "id": "keep-raw-admin-dsl-json-parsing-in-adapters-not-in-this-widget",
      "severity": "recommended",
      "doc": "Keep raw Admin DSL JSON parsing in adapters, not in this widget."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"toolbar\""
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;

/**
 * Scaffold for `Toolbar`.
 *
 * Purpose: Small page/tool action row for legacy or non-workbench pages. It should eventually be a thin ActionGroup wrapper.
 *
 * Adapter boundary: Adapter maps toolbar node actions into ActionViewModel list.
 */
export function Toolbar(props: ToolbarProps) {
  const scaffoldProps = props as ToolbarProps & {
    id?: string;
    className?: string;
    style?: React.CSSProperties;
    dataAttributes?: Record<string, string | number | boolean>;
    children?: ReactNode;
    main?: ReactNode;
    title?: string;
    label?: string;
    name?: string;
    value?: unknown;
  };
  const heading = scaffoldProps.title || scaffoldProps.label || scaffoldProps.name || "Toolbar";
  const dataAttributes = Object.fromEntries(
    Object.entries(scaffoldProps.dataAttributes ?? {}).map(([key, value]) => [`data-${key}`, String(value)]),
  ) as Record<string, string>;

  return (
    <section
      id={scaffoldProps.id}
      className={scaffoldProps.className}
      data-admin-dsl-widget="Toolbar"
      data-admin-dsl-widget-id="admin.layout.toolbar"
      data-admin-dsl-widget-level="molecule"
      style={scaffoldProps.style}
      {...dataAttributes}
    >
      <div style={{ border: "1px solid #dfd2bd", borderRadius: 12, padding: 12, background: "#fffaf0" }}>
        <strong>{heading}</strong>
        <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>{diagnostics.purpose}</p>
        {diagnostics.adapterBoundary ? (
          <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>Adapter: {diagnostics.adapterBoundary}</p>
        ) : null}
        <details style={{ marginTop: 10, fontSize: 12, color: "#6f6254" }}>
          <summary>Widget IR diagnostics</summary>
          <pre style={{ whiteSpace: "pre-wrap", margin: "8px 0 0" }}>{JSON.stringify(diagnostics, null, 2)}</pre>
        </details>
      </div>
      {scaffoldProps.children ? <div style={{ marginTop: 12 }}>{scaffoldProps.children}</div> : null}
      {scaffoldProps.main ? <div style={{ marginTop: 12 }}>{scaffoldProps.main}</div> : null}
    </section>
  );
}
