/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/09-calendar-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.calendar.month-calendar
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type { Meta, StoryObj } from "@storybook/react";
import { MonthCalendar } from "./MonthCalendar";
import type { MonthCalendarProps } from "./MonthCalendar.types";

const defaultArgs = {
  calendarId: "availability",
  month: "2026-06",
  markers: [{ date: "2026-06-12", kind: "available", tone: "success" }],
} as unknown as MonthCalendarProps;

const meta = {
  title: "Admin DSL Widgets/Organisms/MonthCalendar",
  component: MonthCalendar,
  args: defaultArgs,
  parameters: {
    docs: {
      description: {
        component: "MonthCalendar widget.",
      },
    },
  },
} satisfies Meta<typeof MonthCalendar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const DefaultMonth: Story = {
  name: "DefaultMonth",
  parameters: { docs: { description: { story: "Tests the normal month grid for MonthCalendar." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <MonthCalendar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "defaultMonth"
}, asserts: [
  "MonthCalendar renders the DefaultMonth scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const WithPublishedMarkers: Story = {
  name: "WithPublishedMarkers",
  parameters: { docs: { description: { story: "Tests the WithPublishedMarkers scenario for MonthCalendar with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <MonthCalendar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "withPublishedMarkers"
}, asserts: [
  "MonthCalendar renders the WithPublishedMarkers scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const WithScheduledMarkers: Story = {
  name: "WithScheduledMarkers",
  parameters: { docs: { description: { story: "Tests the WithScheduledMarkers scenario for MonthCalendar with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <MonthCalendar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "withScheduledMarkers"
}, asserts: [
  "MonthCalendar renders the WithScheduledMarkers scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const SelectedDate: Story = {
  name: "SelectedDate",
  parameters: { docs: { description: { story: "Tests selected date styling and callback context in MonthCalendar." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <MonthCalendar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "selectedDate"
}, asserts: [
  "MonthCalendar renders the SelectedDate scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const NoActionsReadonly: Story = {
  name: "NoActionsReadonly",
  parameters: { docs: { description: { story: "Tests read-only behavior when MonthCalendar has no actions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <MonthCalendar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "noActionsReadonly"
}, asserts: [
  "MonthCalendar renders the NoActionsReadonly scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const PreviousNextActions: Story = {
  name: "PreviousNextActions",
  parameters: { docs: { description: { story: "Tests previous/next month action slots in MonthCalendar." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <MonthCalendar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "previousNextActions"
}, asserts: [
  "MonthCalendar renders the PreviousNextActions scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const MobileCalendar: Story = {
  name: "MobileCalendar",
  parameters: { docs: { description: { story: "Tests mobile calendar layout for MonthCalendar." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <MonthCalendar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "mobileCalendar"
}, asserts: [
  "MonthCalendar renders the MobileCalendar scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
