/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T01:30:30+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/09-calendar-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: baf8866 2026-05-18T17:21:36-04:00 HAIR-041 Step 50: Regenerate widget scaffolds from schema v2
 * Widget ID: admin.calendar.month-calendar
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

/**
 * Props for MonthCalendar. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface MonthCalendarMarker {
  /**
   * date configures month calendar. Type: string.
   */
  date: string;
  /**
   * kind configures month calendar. Type: string.
   */
  kind: string;
  /**
   * Visual tone used for status, emphasis, or border treatment in MonthCalendar.
   */
  tone?: "success" | "warning" | "danger" | "neutral";
}

/**
 * Props for MonthCalendar. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface MonthCalendarLegendItem {
  /**
   * kind configures month calendar. Type: string.
   */
  kind: string;
  /**
   * Human-readable label rendered by MonthCalendar.
   */
  label: string;
  /**
   * Visual tone used for status, emphasis, or border treatment in MonthCalendar.
   */
  tone?: "success" | "warning" | "danger" | "neutral";
}

/**
 * Props for MonthCalendar. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface MonthCalendarProps extends CommonWidgetProps {
  /**
   * calendarId configures month calendar. Type: string.
   */
  calendarId: string;
  /**
   * Month key rendered by MonthCalendar, typically YYYY-MM.
   */
  month: string;
  /**
   * Human-readable label rendered by MonthCalendar.
   */
  label?: string;
  /**
   * Currently selected date rendered by MonthCalendar.
   */
  selectedDate?: string;
  /**
   * Date markers rendered by MonthCalendar.
   */
  markers?: MonthCalendarMarker[];
  /**
   * Legend entries explaining markers rendered by MonthCalendar.
   */
  legend?: MonthCalendarLegendItem[];
  /**
   * previousMonthAction configures month calendar. Type: ActionViewModel.
   */
  previousMonthAction?: ActionViewModel;
  /**
   * nextMonthAction configures month calendar. Type: ActionViewModel.
   */
  nextMonthAction?: ActionViewModel;
  /**
   * selectDateAction configures month calendar. Type: ActionViewModel.
   */
  selectDateAction?: ActionViewModel;
  /**
   * onMonthAction configures month calendar. Type: CalendarCellActionHandler.
   */
  onMonthAction?: CalendarCellActionHandler;
  /**
   * onSelectDate configures month calendar. Type: CalendarCellActionHandler.
   */
  onSelectDate?: CalendarCellActionHandler;
}
