// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/fringe/dsl/v1/dsl.proto (package fringe.dsl.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Value } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/fringe/dsl/v1/dsl.proto.
 */
export const file_proto_fringe_dsl_v1_dsl: GenFile = /*@__PURE__*/
  fileDesc("Ch1wcm90by9mcmluZ2UvZHNsL3YxL2RzbC5wcm90bxINZnJpbmdlLmRzbC52MSK+AQoEUGFnZRIWCg5zY2hlbWFfdmVyc2lvbhgBIAEoDRIKCgJpZBgCIAEoCRINCgV0aXRsZRgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRIjCgVzaGVsbBgFIAEoCzIULmZyaW5nZS5kc2wudjEuU2hlbGwSIgoFbm9kZXMYBiADKAsyEy5mcmluZ2UuZHNsLnYxLk5vZGUSJQoEbWV0YRgHIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QiPQoFU2hlbGwSDAoEa2luZBgBIAEoCRImCgVwcm9wcxgCIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QiigEKBE5vZGUSDAoEa2luZBgBIAEoCRImCgVwcm9wcxgCIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QSJQoIY2hpbGRyZW4YAyADKAsyEy5mcmluZ2UuZHNsLnYxLk5vZGUSJQoEbWV0YRgEIAEoCzIXLmZyaW5nZS5kc2wudjEuTm9kZU1ldGEigwEKCE5vZGVNZXRhEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSFgoOZGF0YV9jb21wb25lbnQYAyABKAkSFAoMZGF0YV9zZWN0aW9uGAQgASgJEhEKCWRhdGFfcGFydBgFIAEoCRIMCgRub3RlGAYgASgJEg4KBnJlZ2lvbhgHIAEoCSImCglBY3Rpb25SZWYSCgoCaWQYASABKAkSDQoFZXZlbnQYAiABKAkiXwoGRWZmZWN0EgwKBGtpbmQYASABKAkSDAoEdG9uZRgCIAEoCRIPCgdtZXNzYWdlGAMgASgJEigKB3BheWxvYWQYBCABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0IuIBChBJbnRlcmFjdGlvbkV2ZW50EhAKCGV2ZW50X2lkGAEgASgJEhIKCnNlc3Npb25faWQYAiABKAkSFAoMcGFnZV92ZXJzaW9uGAMgASgNEg8KB25vZGVfaWQYBCABKAkSEQoJbm9kZV9raW5kGAUgASgJEhEKCWFjdGlvbl9pZBgGIAEoCRINCgVldmVudBgHIAEoCRIlCgV2YWx1ZRgIIAEoCzIWLmdvb2dsZS5wcm90b2J1Zi5WYWx1ZRIlCgRtZXRhGAkgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdCJLChBTdGFydEZsb3dSZXF1ZXN0Eg8KB2Zsb3dfaWQYASABKAkSJgoFaW5wdXQYAiABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0IiQKDkdldEZsb3dSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkiWgoURGlzcGF0Y2hFdmVudFJlcXVlc3QSEgoKc2Vzc2lvbl9pZBgBIAEoCRIuCgVldmVudBgCIAEoCzIfLmZyaW5nZS5kc2wudjEuSW50ZXJhY3Rpb25FdmVudCKAAQoJRmxvd1N0YXRlEhIKCnNlc3Npb25faWQYASABKAkSFAoMcGFnZV92ZXJzaW9uGAIgASgNEiEKBHBhZ2UYAyABKAsyEy5mcmluZ2UuZHNsLnYxLlBhZ2USJgoHZWZmZWN0cxgEIAMoCzIVLmZyaW5nZS5kc2wudjEuRWZmZWN0IlMKCERzbEVycm9yEgwKBGNvZGUYASABKAkSDwoHbWVzc2FnZRgCIAEoCRIoCgdkZXRhaWxzGAMgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdEJEWkJnaXRodWIuY29tL2dvLWdvLWdvbGVtcy9oYWlyLWJvb2tpbmcvZ2VuL3Byb3RvL2ZyaW5nZS9kc2wvdjE7ZHNsdjFiBnByb3RvMw", [file_google_protobuf_struct]);

/**
 * Page is the stable transport envelope for a backend-authored DSL page.
 * Widget-specific props remain dynamic in this first protobuf spike so the
 * React DSL can keep evolving without regenerating every node prop message.
 *
 * @generated from message fringe.dsl.v1.Page
 */
export type Page = Message<"fringe.dsl.v1.Page"> & {
  /**
   * @generated from field: uint32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: fringe.dsl.v1.Shell shell = 5;
   */
  shell?: Shell | undefined;

  /**
   * @generated from field: repeated fringe.dsl.v1.Node nodes = 6;
   */
  nodes: Node[];

  /**
   * @generated from field: google.protobuf.Struct meta = 7;
   */
  meta?: JsonObject | undefined;
};

/**
 * Describes the message fringe.dsl.v1.Page.
 * Use `create(PageSchema)` to create a new message.
 */
export const PageSchema: GenMessage<Page> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 0);

/**
 * @generated from message fringe.dsl.v1.Shell
 */
export type Shell = Message<"fringe.dsl.v1.Shell"> & {
  /**
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: google.protobuf.Struct props = 2;
   */
  props?: JsonObject | undefined;
};

/**
 * Describes the message fringe.dsl.v1.Shell.
 * Use `create(ShellSchema)` to create a new message.
 */
export const ShellSchema: GenMessage<Shell> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 1);

/**
 * @generated from message fringe.dsl.v1.Node
 */
export type Node = Message<"fringe.dsl.v1.Node"> & {
  /**
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: google.protobuf.Struct props = 2;
   */
  props?: JsonObject | undefined;

  /**
   * @generated from field: repeated fringe.dsl.v1.Node children = 3;
   */
  children: Node[];

  /**
   * @generated from field: fringe.dsl.v1.NodeMeta meta = 4;
   */
  meta?: NodeMeta | undefined;
};

/**
 * Describes the message fringe.dsl.v1.Node.
 * Use `create(NodeSchema)` to create a new message.
 */
export const NodeSchema: GenMessage<Node> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 2);

/**
 * @generated from message fringe.dsl.v1.NodeMeta
 */
export type NodeMeta = Message<"fringe.dsl.v1.NodeMeta"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string data_component = 3;
   */
  dataComponent: string;

  /**
   * @generated from field: string data_section = 4;
   */
  dataSection: string;

  /**
   * @generated from field: string data_part = 5;
   */
  dataPart: string;

  /**
   * @generated from field: string note = 6;
   */
  note: string;

  /**
   * @generated from field: string region = 7;
   */
  region: string;
};

/**
 * Describes the message fringe.dsl.v1.NodeMeta.
 * Use `create(NodeMetaSchema)` to create a new message.
 */
export const NodeMetaSchema: GenMessage<NodeMeta> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 3);

/**
 * ActionRef is the opaque browser-visible reference to a backend callback.
 * It is normally embedded inside Node.props.actions or Shell.props.actions in
 * the current JSON contract; this typed message documents the shape.
 *
 * @generated from message fringe.dsl.v1.ActionRef
 */
export type ActionRef = Message<"fringe.dsl.v1.ActionRef"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string event = 2;
   */
  event: string;
};

/**
 * Describes the message fringe.dsl.v1.ActionRef.
 * Use `create(ActionRefSchema)` to create a new message.
 */
export const ActionRefSchema: GenMessage<ActionRef> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 4);

/**
 * @generated from message fringe.dsl.v1.Effect
 */
export type Effect = Message<"fringe.dsl.v1.Effect"> & {
  /**
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: string tone = 2;
   */
  tone: string;

  /**
   * @generated from field: string message = 3;
   */
  message: string;

  /**
   * @generated from field: google.protobuf.Struct payload = 4;
   */
  payload?: JsonObject | undefined;
};

/**
 * Describes the message fringe.dsl.v1.Effect.
 * Use `create(EffectSchema)` to create a new message.
 */
export const EffectSchema: GenMessage<Effect> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 5);

/**
 * @generated from message fringe.dsl.v1.InteractionEvent
 */
export type InteractionEvent = Message<"fringe.dsl.v1.InteractionEvent"> & {
  /**
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * @generated from field: string session_id = 2;
   */
  sessionId: string;

  /**
   * @generated from field: uint32 page_version = 3;
   */
  pageVersion: number;

  /**
   * @generated from field: string node_id = 4;
   */
  nodeId: string;

  /**
   * @generated from field: string node_kind = 5;
   */
  nodeKind: string;

  /**
   * @generated from field: string action_id = 6;
   */
  actionId: string;

  /**
   * @generated from field: string event = 7;
   */
  event: string;

  /**
   * @generated from field: google.protobuf.Value value = 8;
   */
  value?: Value | undefined;

  /**
   * @generated from field: google.protobuf.Struct meta = 9;
   */
  meta?: JsonObject | undefined;
};

/**
 * Describes the message fringe.dsl.v1.InteractionEvent.
 * Use `create(InteractionEventSchema)` to create a new message.
 */
export const InteractionEventSchema: GenMessage<InteractionEvent> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 6);

/**
 * @generated from message fringe.dsl.v1.StartFlowRequest
 */
export type StartFlowRequest = Message<"fringe.dsl.v1.StartFlowRequest"> & {
  /**
   * @generated from field: string flow_id = 1;
   */
  flowId: string;

  /**
   * @generated from field: google.protobuf.Struct input = 2;
   */
  input?: JsonObject | undefined;
};

/**
 * Describes the message fringe.dsl.v1.StartFlowRequest.
 * Use `create(StartFlowRequestSchema)` to create a new message.
 */
export const StartFlowRequestSchema: GenMessage<StartFlowRequest> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 7);

/**
 * @generated from message fringe.dsl.v1.GetFlowRequest
 */
export type GetFlowRequest = Message<"fringe.dsl.v1.GetFlowRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message fringe.dsl.v1.GetFlowRequest.
 * Use `create(GetFlowRequestSchema)` to create a new message.
 */
export const GetFlowRequestSchema: GenMessage<GetFlowRequest> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 8);

/**
 * @generated from message fringe.dsl.v1.DispatchEventRequest
 */
export type DispatchEventRequest = Message<"fringe.dsl.v1.DispatchEventRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: fringe.dsl.v1.InteractionEvent event = 2;
   */
  event?: InteractionEvent | undefined;
};

/**
 * Describes the message fringe.dsl.v1.DispatchEventRequest.
 * Use `create(DispatchEventRequestSchema)` to create a new message.
 */
export const DispatchEventRequestSchema: GenMessage<DispatchEventRequest> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 9);

/**
 * FlowState is the canonical successful response envelope for the DSL flow API.
 *
 * @generated from message fringe.dsl.v1.FlowState
 */
export type FlowState = Message<"fringe.dsl.v1.FlowState"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: uint32 page_version = 2;
   */
  pageVersion: number;

  /**
   * @generated from field: fringe.dsl.v1.Page page = 3;
   */
  page?: Page | undefined;

  /**
   * @generated from field: repeated fringe.dsl.v1.Effect effects = 4;
   */
  effects: Effect[];
};

/**
 * Describes the message fringe.dsl.v1.FlowState.
 * Use `create(FlowStateSchema)` to create a new message.
 */
export const FlowStateSchema: GenMessage<FlowState> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 10);

/**
 * DslError is the canonical error envelope for DSL flow API failures.
 *
 * @generated from message fringe.dsl.v1.DslError
 */
export type DslError = Message<"fringe.dsl.v1.DslError"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: google.protobuf.Struct details = 3;
   */
  details?: JsonObject | undefined;
};

/**
 * Describes the message fringe.dsl.v1.DslError.
 * Use `create(DslErrorSchema)` to create a new message.
 */
export const DslErrorSchema: GenMessage<DslError> = /*@__PURE__*/
  messageDesc(file_proto_fringe_dsl_v1_dsl, 11);

