/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T01:30:30+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/08-media-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.media.preview-frame
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for PreviewFrame.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const previewFrameWidgetMetadata = {
  "widgetId": "admin.media.preview-frame",
  "name": "PreviewFrame",
  "category": "media_widgets",
  "classification": {
    "level": "organism",
    "description": "PreviewFrame participates in the Admin DSL component system as a organism; its level controls scaffold location and Storybook grouping."
  },
  "purpose": "PreviewFrame widget.",
  "designRationale": "PreviewFrame extracts a named React boundary from the old Admin DSL renderer so behavior, stories, styling, and action context can be reviewed independently.",
  "adapterBoundary": "The Admin DSL adapter should convert raw node props/actions into typed PreviewFrame props. PreviewFrame should not parse AdminNode JSON or call backend dispatch helpers directly.",
  "implementationNotes": [
    "Implement PreviewFrame using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure PreviewFrame exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "previewActions": {
      "doc": "previewActions action slot for PreviewFrame. The widget emits the declared context through onAction and adapters lower it to runtime dispatch.",
      "callback": "onAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "PreviewactionsContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the previewActions slot on PreviewFrame."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "Adapter lowers this typed callback into Admin DSL dispatch."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by PreviewFrame. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed PreviewFrame props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<PreviewFrame />"
    }
  },
  "stories": {
    "IframeConnected": {
      "doc": "Tests the IframeConnected scenario for PreviewFrame with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "iframeConnected"
      },
      "asserts": [
        "PreviewFrame renders the IframeConnected scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "Placeholder": {
      "doc": "Tests the Placeholder scenario for PreviewFrame with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "placeholder"
      },
      "asserts": [
        "PreviewFrame renders the Placeholder scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "WithBodyAndActions": {
      "doc": "Tests the WithBodyAndActions scenario for PreviewFrame with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "withBodyAndActions"
      },
      "asserts": [
        "PreviewFrame renders the WithBodyAndActions scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "TallPreview": {
      "doc": "Tests the TallPreview scenario for PreviewFrame with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "tallPreview"
      },
      "asserts": [
        "PreviewFrame renders the TallPreview scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "MobilePreview": {
      "doc": "Tests the MobilePreview scenario for PreviewFrame with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "mobilePreview"
      },
      "asserts": [
        "PreviewFrame renders the MobilePreview scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"previewFrame\""
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;
