/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T01:30:30+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/08-media-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: baf8866 2026-05-18T17:21:36-04:00 HAIR-041 Step 50: Regenerate widget scaffolds from schema v2
 * Widget ID: admin.media.preview-frame
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

/**
 * Props for PreviewFrame. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface PreviewFrameProps extends CommonWidgetProps {
  /**
   * previewId configures preview frame. Type: string.
   */
  previewId: string;
  /**
   * kicker configures preview frame. Type: string.
   */
  kicker?: string;
  /**
   * Primary heading or title rendered by PreviewFrame.
   */
  title: string;
  /**
   * Optional body copy rendered by PreviewFrame.
   */
  body?: string;
  /**
   * External or internal URL rendered by PreviewFrame.
   */
  url?: string;
  /**
   * Preferred preview height for PreviewFrame.
   */
  height?: number;
  /**
   * Placeholder text for the empty input state in PreviewFrame.
   */
  placeholder?: string;
  /**
   * Ordered action list for the PreviewFrame slot. Presentation should be derived from semantic slot and action intent.
   */
  actions?: ActionViewModel[];
  /**
   * Callback invoked by PreviewFrame with action metadata and typed context.
   */
  onAction?: PanelActionHandler;
}
