/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T01:30:30+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/07-data-display-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.data-display.metric-card
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for MetricCard.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const metricCardWidgetMetadata = {
  "widgetId": "admin.data-display.metric-card",
  "name": "MetricCard",
  "category": "data_display_widgets",
  "classification": {
    "level": "molecule",
    "description": "MetricCard participates in the Admin DSL component system as a molecule; its level controls scaffold location and Storybook grouping."
  },
  "purpose": "MetricCard widget.",
  "designRationale": "MetricCard extracts a named React boundary from the old Admin DSL renderer so behavior, stories, styling, and action context can be reviewed independently.",
  "adapterBoundary": "The Admin DSL adapter should convert raw node props/actions into typed MetricCard props. MetricCard should not parse AdminNode JSON or call backend dispatch helpers directly.",
  "implementationNotes": [
    "Implement MetricCard using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure MetricCard exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {},
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by MetricCard. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed MetricCard props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<MetricCard />"
    }
  },
  "stories": {
    "Default": {
      "doc": "Tests the baseline MetricCard rendering with representative production-like data.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "default"
      },
      "asserts": [
        "MetricCard renders the Default scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "SuccessTone": {
      "doc": "Tests the SuccessTone scenario for MetricCard with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "successTone"
      },
      "asserts": [
        "MetricCard renders the SuccessTone scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "WarningTone": {
      "doc": "Tests the WarningTone scenario for MetricCard with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "warningTone"
      },
      "asserts": [
        "MetricCard renders the WarningTone scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "DangerTone": {
      "doc": "Tests the DangerTone scenario for MetricCard with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "dangerTone"
      },
      "asserts": [
        "MetricCard renders the DangerTone scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "LongCaption": {
      "doc": "Tests the LongCaption scenario for MetricCard with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "longCaption"
      },
      "asserts": [
        "MetricCard renders the LongCaption scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"metricCard\""
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;
