/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T01:30:30+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/07-data-display-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: baf8866 2026-05-18T17:21:36-04:00 HAIR-041 Step 50: Regenerate widget scaffolds from schema v2
 * Widget ID: admin.data-display.metric-card
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type { ReactNode } from "react";
import { metricCardWidgetMetadata } from "./MetricCard.metadata";
import type { MetricCardProps } from "./MetricCard.types";

/**
 * Scaffold for `MetricCard`.
 *
 * Purpose: MetricCard widget.
 *
 * Adapter boundary: The Admin DSL adapter should convert raw node props/actions into typed MetricCard props. MetricCard should not parse AdminNode JSON or call backend dispatch helpers directly.
 */
export function MetricCard(props: MetricCardProps) {
  const scaffoldProps = props as MetricCardProps & {
    id?: string;
    className?: string;
    style?: React.CSSProperties;
    dataAttributes?: Record<string, string | number | boolean>;
    children?: ReactNode;
    main?: ReactNode;
    title?: string;
    label?: string;
    name?: string;
    value?: unknown;
  };
  const heading = scaffoldProps.title || scaffoldProps.label || scaffoldProps.name || "MetricCard";
  const dataAttributes = Object.fromEntries(
    Object.entries(scaffoldProps.dataAttributes ?? {}).map(([key, value]) => [`data-${key}`, String(value)]),
  ) as Record<string, string>;

  return (
    <section
      id={scaffoldProps.id}
      className={scaffoldProps.className}
      data-admin-dsl-widget="MetricCard"
      data-admin-dsl-widget-id={metricCardWidgetMetadata.widgetId}
      data-admin-dsl-widget-level="molecule"
      style={scaffoldProps.style}
      {...dataAttributes}
    >
      <div style={{ border: "1px solid #dfd2bd", borderRadius: 12, padding: 12, background: "#fffaf0" }}>
        <strong>{heading}</strong>
        <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>{metricCardWidgetMetadata.purpose}</p>
        {metricCardWidgetMetadata.adapterBoundary ? (
          <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>Adapter: {metricCardWidgetMetadata.adapterBoundary}</p>
        ) : null}
        <details style={{ marginTop: 10, fontSize: 12, color: "#6f6254" }}>
          <summary>Widget IR metadata</summary>
          <pre style={{ whiteSpace: "pre-wrap", margin: "8px 0 0" }}>{JSON.stringify(metricCardWidgetMetadata, null, 2)}</pre>
        </details>
      </div>
      {scaffoldProps.children ? <div style={{ marginTop: 12 }}>{scaffoldProps.children}</div> : null}
      {scaffoldProps.main ? <div style={{ marginTop: 12 }}>{scaffoldProps.main}</div> : null}
    </section>
  );
}
