/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/04-action-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.action.action-button
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

/**
 * Props for ActionButton. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface ActionButtonProps<C = unknown> extends CommonWidgetProps {
  /**
   * Action metadata rendered or invoked by ActionButton. The widget receives metadata only; adapters own backend dispatch.
   */
  action: ActionViewModel;
  /**
   * Typed contextual payload passed back when ActionButton invokes an action.
   */
  context?: C;
  /**
   * Visual variant for ActionButton; this should select a design-system treatment without changing action semantics.
   */
  variant?: "solid" | "soft" | "subtle" | "danger" | "overflow";
  /**
   * Size/touch-target variant for ActionButton. Mobile stories should verify minimum usable targets.
   */
  size?: "sm" | "md" | "touch";
  /**
   * Callback invoked by ActionButton with action metadata and typed context.
   */
  onAction?: (action: ActionViewModel, context: C) => void;
}
