/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/04-action-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.action.action-button
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type { ReactNode } from "react";
import type { ActionButtonProps } from "./ActionButton.types";

const diagnostics = {
  "widgetId": "admin.action.action-button",
  "purpose": "Render one action with consistent disabled, loading, primary, danger, subtle, and placement-aware styling.",
  "adapterBoundary": "The widget receives an ActionViewModel and context. It should not know AdminNode or dispatchAdminAction directly.",
  "implementationNotes": [
    "Implement ActionButton using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure ActionButton exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "self": {
      "doc": "The caller chooses the semantic slot and passes an onAction callback; ActionButton only renders and invokes.",
      "callback": "onAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "SelfContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the self slot on ActionButton."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by ActionButton. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed ActionButton props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<ActionButton />"
    }
  },
  "implementationTodos": [
    {
      "id": "replace-placeholder-with-actual-button-element-styles-from-desig",
      "severity": "required",
      "doc": "Replace placeholder with actual button element styles from design tokens."
    },
    {
      "id": "map-variant-slot-semantics-without-reintroducing-placement-speci",
      "severity": "recommended",
      "doc": "Map variant/slot semantics without reintroducing placement-specific conditionals everywhere."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "renderActions button branch in web/src/admin-dsl/render.tsx plus row/bulk/search special buttons"
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current source referenced by the v1 widget IR."
      }
    ]
  }
} as const;

/**
 * Scaffold for `ActionButton`.
 *
 * Purpose: Render one action with consistent disabled, loading, primary, danger, subtle, and placement-aware styling.
 *
 * Adapter boundary: The widget receives an ActionViewModel and context. It should not know AdminNode or dispatchAdminAction directly.
 */
export function ActionButton(props: ActionButtonProps) {
  const scaffoldProps = props as ActionButtonProps & {
    id?: string;
    className?: string;
    style?: React.CSSProperties;
    dataAttributes?: Record<string, string | number | boolean>;
    children?: ReactNode;
    main?: ReactNode;
    title?: string;
    label?: string;
    name?: string;
    value?: unknown;
  };
  const heading = scaffoldProps.title || scaffoldProps.label || scaffoldProps.name || "ActionButton";
  const dataAttributes = Object.fromEntries(
    Object.entries(scaffoldProps.dataAttributes ?? {}).map(([key, value]) => [`data-${key}`, String(value)]),
  ) as Record<string, string>;

  return (
    <section
      id={scaffoldProps.id}
      className={scaffoldProps.className}
      data-admin-dsl-widget="ActionButton"
      data-admin-dsl-widget-id="admin.action.action-button"
      data-admin-dsl-widget-level="atom"
      style={scaffoldProps.style}
      {...dataAttributes}
    >
      <div style={{ border: "1px solid #dfd2bd", borderRadius: 12, padding: 12, background: "#fffaf0" }}>
        <strong>{heading}</strong>
        <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>{diagnostics.purpose}</p>
        {diagnostics.adapterBoundary ? (
          <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>Adapter: {diagnostics.adapterBoundary}</p>
        ) : null}
        <details style={{ marginTop: 10, fontSize: 12, color: "#6f6254" }}>
          <summary>Widget IR diagnostics</summary>
          <pre style={{ whiteSpace: "pre-wrap", margin: "8px 0 0" }}>{JSON.stringify(diagnostics, null, 2)}</pre>
        </details>
      </div>
      {scaffoldProps.children ? <div style={{ marginTop: 12 }}>{scaffoldProps.children}</div> : null}
      {scaffoldProps.main ? <div style={{ marginTop: 12 }}>{scaffoldProps.main}</div> : null}
    </section>
  );
}
