/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T22:42:09+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/04-action-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: e4a9d9e 2026-05-18 HAIR-041 Step 63: Refresh action widget scaffolds
 * Widget ID: admin.action.action-button
 *
 * This file started as generated schema-v2 scaffold output. The visual button
 * implementation below was extracted from renderActions in web/src/admin-dsl/render.tsx
 * so action styling can be shared by renderer adapters and standalone widgets.
 */
import { actionButtonWidgetMetadata } from "./ActionButton.metadata";
import type { ActionButtonProps } from "./ActionButton.types";
import { actionButtonStyle, actionDataAttributes, dataAttrsFromRecord, inferActionSize, inferActionVariant, widgetDataAttributes } from "../../shared";

export function ActionButton<C = unknown>({
  id,
  className,
  style,
  dataAttributes,
  action,
  context,
  variant: explicitVariant,
  size = "md",
  onAction,
}: ActionButtonProps<C>) {
  const disabled = Boolean(action.disabled);
  const loading = Boolean(action.loading);
  const placement = typeof action.placement === "string" ? action.placement : undefined;
  const variant = inferActionVariant(action, explicitVariant);
  const actionSize = inferActionSize(action, size);
  const label = loading ? "Working…" : action.label || action.target;
  const dataAttrs = dataAttrsFromRecord(dataAttributes);

  return (
    <button
      id={id}
      type="button"
      className={["adminDslActionButton", className].filter(Boolean).join(" ") || undefined}
      disabled={disabled || loading}
      aria-label={action.accessibilityLabel || action.label || action.target}
      aria-busy={loading || undefined}
      {...widgetDataAttributes(actionButtonWidgetMetadata.widgetId)}
      {...actionDataAttributes(action)}
      onClick={(event) => {
        if (disabled || loading) return;
        const formValues = event.currentTarget.form ? Object.fromEntries(new FormData(event.currentTarget.form).entries()) : undefined;
        onAction?.(action, (formValues ?? context) as C);
      }}
      style={{ ...actionButtonStyle({ variant, size: actionSize, disabled, loading }), ...style }}
      {...dataAttrs}
    >
      {variant === "overflow" ? <span aria-hidden="true">…</span> : label}
      {variant === "subtle" && placement !== "panelFooter" ? <span aria-hidden="true">→</span> : null}
    </button>
  );
}
