/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/04-action-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: ActionButton
 * Category: action_widgets
 * Classification: {"level": "atom"}
 * Current source inventory: renderActions button branch in web/src/admin-dsl/render.tsx plus row/bulk/search special buttons
 *
 * Purpose:
 * Render one action with consistent disabled, loading, primary, danger, subtle, and placement-aware styling.
 *
 * Human notes from YAML:
 * {
 *   "intent": "Unifies visual treatment for action metadata so primary, danger, subtle, loading, disabled, and touch-target rules do not get reimplemented in every table/panel/form branch.",
 *   "adapter_boundary": "The widget receives an ActionViewModel and context. It should not know AdminNode or dispatchAdminAction directly.",
 *   "slot_intent": {
 *     "self": "The caller chooses the semantic slot and passes an onAction callback; ActionButton only renders and invokes."
 *   },
 *   "storybook_intent": "Stories should pin visual variants and prevent regressions in button shape, subtle row links, danger styling, and loading/disabled states."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "self",
 *     "notes": "The widget executes the action it receives through onAction.",
 *     "callback_prop": "onAction",
 *     "intent": "The caller chooses the semantic slot and passes an onAction callback; ActionButton only renders and invokes.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Replace placeholder with actual button element styles from design tokens.
 * - XXX: Map variant/slot semantics without reintroducing placement-specific conditionals everywhere.
 */
import type * as React from "react";
import type { ReactNode } from "react";
import type { ActionButtonProps } from "./ActionButton.types";

const widgetClassification = "{\"level\": \"atom\"}";
const widgetPurpose = "Render one action with consistent disabled, loading, primary, danger, subtle, and placement-aware styling.";
const widgetHumanNotes = "{\n  \"intent\": \"Unifies visual treatment for action metadata so primary, danger, subtle, loading, disabled, and touch-target rules do not get reimplemented in every table/panel/form branch.\",\n  \"adapter_boundary\": \"The widget receives an ActionViewModel and context. It should not know AdminNode or dispatchAdminAction directly.\",\n  \"slot_intent\": {\n    \"self\": \"The caller chooses the semantic slot and passes an onAction callback; ActionButton only renders and invokes.\"\n  },\n  \"storybook_intent\": \"Stories should pin visual variants and prevent regressions in button shape, subtle row links, danger styling, and loading/disabled states.\"\n}";
const widgetActionSlots = "[\n  {\n    \"name\": \"self\",\n    \"notes\": \"The widget executes the action it receives through onAction.\",\n    \"callback_prop\": \"onAction\",\n    \"intent\": \"The caller chooses the semantic slot and passes an onAction callback; ActionButton only renders and invokes.\",\n    \"implementation_note\": \"The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport.\"\n  }\n]";
const widgetXxx = "XXX: Replace placeholder with actual button element styles from design tokens.\nXXX: Map variant/slot semantics without reintroducing placement-specific conditionals everywhere.";

/**
 * Scaffold for `ActionButton`.
 *
 * Generated from `/home/manuel/workspaces/2026-04-21/hair-v2/hair-booking/ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/04-action-widgets.yaml`.
 * Current source inventory: renderActions button branch in web/src/admin-dsl/render.tsx plus row/bulk/search special buttons.
 *
 * XXX: Replace this placeholder body with the real visual implementation. Keep
 * raw Admin DSL node decoding in renderer adapters; this component should
 * receive typed widget props only.
 */
export function ActionButton(props: ActionButtonProps) {
  const scaffoldProps = props as ActionButtonProps & {
    id?: string;
    className?: string;
    style?: React.CSSProperties;
    children?: ReactNode;
    title?: string;
    label?: string;
    name?: string;
    value?: unknown;
  };
  const heading = scaffoldProps.title || scaffoldProps.label || scaffoldProps.name || "ActionButton";

  return (
    <section
      id={scaffoldProps.id}
      className={scaffoldProps.className}
      data-admin-dsl-widget="ActionButton"
      data-admin-dsl-widget-level="atom"
      style={scaffoldProps.style}
    >
      <div style={{ border: "1px dashed #c8b89b", borderRadius: 12, padding: 12, background: "#fffaf0" }}>
        <strong>{heading}</strong>
        <div style={{ marginTop: 4, fontSize: 12, color: "#6f6254" }}>
          ActionButton scaffold — XXX replace with final implementation.
        </div>
        <dl style={{ margin: "10px 0 0", display: "grid", gap: 6, fontSize: 12, color: "#6f6254" }}>
          <div><dt style={{ fontWeight: 700 }}>Classification</dt><dd style={{ margin: 0, whiteSpace: "pre-wrap" }}>{widgetClassification}</dd></div>
          <div><dt style={{ fontWeight: 700 }}>Purpose</dt><dd style={{ margin: 0, whiteSpace: "pre-wrap" }}>{widgetPurpose}</dd></div>
          <div><dt style={{ fontWeight: 700 }}>Human notes</dt><dd style={{ margin: 0, whiteSpace: "pre-wrap" }}>{widgetHumanNotes}</dd></div>
          <div><dt style={{ fontWeight: 700 }}>Action slots</dt><dd style={{ margin: 0, whiteSpace: "pre-wrap" }}>{widgetActionSlots}</dd></div>
          <div><dt style={{ fontWeight: 700 }}>Implementation warnings</dt><dd style={{ margin: 0, whiteSpace: "pre-wrap" }}>{widgetXxx}</dd></div>
        </dl>
      </div>
      {scaffoldProps.children ? <div style={{ marginTop: 12 }}>{scaffoldProps.children}</div> : null}
    </section>
  );
}
