/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/11-surface-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.surface.overlay-surface
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type { ReactNode } from "react";
import type { OverlaySurfaceProps } from "./OverlaySurface.types";

const diagnostics = {
  "widgetId": "admin.surface.overlay-surface",
  "purpose": "OverlaySurface widget.",
  "adapterBoundary": "The Admin DSL adapter should convert raw node props/actions into typed OverlaySurface props. OverlaySurface should not parse AdminNode JSON or call backend dispatch helpers directly.",
  "implementationNotes": [
    "Implement OverlaySurface using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure OverlaySurface exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "close": {
      "doc": "close action slot for OverlaySurface. The widget emits the declared context through onAction and adapters lower it to runtime dispatch.",
      "callback": "onAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "CloseContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the close slot on OverlaySurface."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "Adapter lowers this typed callback into Admin DSL dispatch."
      }
    },
    "footer": {
      "doc": "footer action slot for OverlaySurface. The widget emits the declared context through onAction and adapters lower it to runtime dispatch.",
      "callback": "onAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "FooterContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the footer slot on OverlaySurface."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "Adapter lowers this typed callback into Admin DSL dispatch."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by OverlaySurface. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed OverlaySurface props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<OverlaySurface />"
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "shared branch for modal, drawer, sheet, detailPanel, inlinePanel"
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;

/**
 * Scaffold for `OverlaySurface`.
 *
 * Purpose: OverlaySurface widget.
 *
 * Adapter boundary: The Admin DSL adapter should convert raw node props/actions into typed OverlaySurface props. OverlaySurface should not parse AdminNode JSON or call backend dispatch helpers directly.
 */
export function OverlaySurface(props: OverlaySurfaceProps) {
  const scaffoldProps = props as OverlaySurfaceProps & {
    id?: string;
    className?: string;
    style?: React.CSSProperties;
    dataAttributes?: Record<string, string | number | boolean>;
    children?: ReactNode;
    main?: ReactNode;
    title?: string;
    label?: string;
    name?: string;
    value?: unknown;
  };
  const heading = scaffoldProps.title || scaffoldProps.label || scaffoldProps.name || "OverlaySurface";
  const dataAttributes = Object.fromEntries(
    Object.entries(scaffoldProps.dataAttributes ?? {}).map(([key, value]) => [`data-${key}`, String(value)]),
  ) as Record<string, string>;

  return (
    <section
      id={scaffoldProps.id}
      className={scaffoldProps.className}
      data-admin-dsl-widget="OverlaySurface"
      data-admin-dsl-widget-id="admin.surface.overlay-surface"
      data-admin-dsl-widget-level="organism"
      style={scaffoldProps.style}
      {...dataAttributes}
    >
      <div style={{ border: "1px solid #dfd2bd", borderRadius: 12, padding: 12, background: "#fffaf0" }}>
        <strong>{heading}</strong>
        <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>{diagnostics.purpose}</p>
        {diagnostics.adapterBoundary ? (
          <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>Adapter: {diagnostics.adapterBoundary}</p>
        ) : null}
        <details style={{ marginTop: 10, fontSize: 12, color: "#6f6254" }}>
          <summary>Widget IR diagnostics</summary>
          <pre style={{ whiteSpace: "pre-wrap", margin: "8px 0 0" }}>{JSON.stringify(diagnostics, null, 2)}</pre>
        </details>
      </div>
      {scaffoldProps.children ? <div style={{ marginTop: 12 }}>{scaffoldProps.children}</div> : null}
      {scaffoldProps.main ? <div style={{ marginTop: 12 }}>{scaffoldProps.main}</div> : null}
    </section>
  );
}
