/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.resource.bulk-action-bar
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type { ReactNode } from "react";
import type { BulkActionBarProps } from "./BulkActionBar.types";

const diagnostics = {
  "widgetId": "admin.resource.bulk-action-bar",
  "purpose": "Owns the selected/visible-row action strip and visual hierarchy for table-level operations.",
  "adapterBoundary": "ResourceTable computes selected/visible context and passes it down; BulkActionBar only renders and invokes bulk callbacks.",
  "implementationNotes": [
    "Implement BulkActionBar using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure BulkActionBar exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "bulkToolbar": {
      "doc": "Bulk toolbar actions are table-selection actions, not page or row actions.",
      "callback": "onBulkAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "BulktoolbarContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Context described in v1 IR as: visible/selected/allMatching rows"
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by BulkActionBar. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed BulkActionBar props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<BulkActionBar />"
    }
  },
  "implementationTodos": [
    {
      "id": "define-selected-row-disabled-behavior-before-production-use",
      "severity": "required",
      "doc": "Define selected-row disabled behavior before production use."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "bulk action bar inside resourceTable branch"
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;

/**
 * Scaffold for `BulkActionBar`.
 *
 * Purpose: Owns the selected/visible-row action strip and visual hierarchy for table-level operations.
 *
 * Adapter boundary: ResourceTable computes selected/visible context and passes it down; BulkActionBar only renders and invokes bulk callbacks.
 */
export function BulkActionBar(props: BulkActionBarProps) {
  const scaffoldProps = props as BulkActionBarProps & {
    id?: string;
    className?: string;
    style?: React.CSSProperties;
    dataAttributes?: Record<string, string | number | boolean>;
    children?: ReactNode;
    main?: ReactNode;
    title?: string;
    label?: string;
    name?: string;
    value?: unknown;
  };
  const heading = scaffoldProps.title || scaffoldProps.label || scaffoldProps.name || "BulkActionBar";
  const dataAttributes = Object.fromEntries(
    Object.entries(scaffoldProps.dataAttributes ?? {}).map(([key, value]) => [`data-${key}`, String(value)]),
  ) as Record<string, string>;

  return (
    <section
      id={scaffoldProps.id}
      className={scaffoldProps.className}
      data-admin-dsl-widget="BulkActionBar"
      data-admin-dsl-widget-id="admin.resource.bulk-action-bar"
      data-admin-dsl-widget-level="molecule"
      style={scaffoldProps.style}
      {...dataAttributes}
    >
      <div style={{ border: "1px solid #dfd2bd", borderRadius: 12, padding: 12, background: "#fffaf0" }}>
        <strong>{heading}</strong>
        <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>{diagnostics.purpose}</p>
        {diagnostics.adapterBoundary ? (
          <p style={{ margin: "6px 0 0", fontSize: 12, color: "#6f6254" }}>Adapter: {diagnostics.adapterBoundary}</p>
        ) : null}
        <details style={{ marginTop: 10, fontSize: 12, color: "#6f6254" }}>
          <summary>Widget IR diagnostics</summary>
          <pre style={{ whiteSpace: "pre-wrap", margin: "8px 0 0" }}>{JSON.stringify(diagnostics, null, 2)}</pre>
        </details>
      </div>
      {scaffoldProps.children ? <div style={{ marginTop: 12 }}>{scaffoldProps.children}</div> : null}
      {scaffoldProps.main ? <div style={{ marginTop: 12 }}>{scaffoldProps.main}</div> : null}
    </section>
  );
}
