/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: BulkActionBar
 * Category: resource_widgets
 * Classification: {"level": "molecule"}
 * Current source inventory: bulk action bar inside resourceTable branch
 *
 * Human notes from YAML:
 * {
 *   "intent": "Owns the selected/visible-row action strip and visual hierarchy for table-level operations.",
 *   "adapter_boundary": "ResourceTable computes selected/visible context and passes it down; BulkActionBar only renders and invokes bulk callbacks.",
 *   "slot_intent": {
 *     "bulkToolbar": "Bulk toolbar actions are table-selection actions, not page or row actions."
 *   },
 *   "storybook_intent": "Stories should cover selected vs visible scope, disabled no-selection state, primary and danger actions."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "bulkToolbar",
 *     "context": "visible/selected/allMatching rows",
 *     "callback_prop": "onBulkAction",
 *     "intent": "Bulk toolbar actions are table-selection actions, not page or row actions.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Define selected-row disabled behavior before production use.
 */
// XXX: Replace generated defaultArgs with purposeful fixtures for every planned story before treating this as visual coverage.
import type { Meta, StoryObj } from "@storybook/react";
import { BulkActionBar } from "./BulkActionBar";
import type { BulkActionBarProps } from "./BulkActionBar.types";

const defaultArgs = {
  tableId: "requests",
  label: "3 visible requests",
  rows: [{ id: "req_1" }, { id: "req_2" }],
  selectedRowIds: ["req_1"],
  actions: [{ type: "mutation", target: "requests.assign", label: "Assign" }],
} as unknown as BulkActionBarProps;

const meta = {
  title: "Admin DSL Widgets/Molecules/BulkActionBar",
  component: BulkActionBar,
  args: defaultArgs,
} satisfies Meta<typeof BulkActionBar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const VisibleRowsScope: Story = {};
export const SelectedRowsScope: Story = {};
export const PrimaryBulkAction: Story = {};
export const DangerBulkAction: Story = {};
export const NoSelectionDisabled: Story = {};
