/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T00:32:13+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: baf8866 2026-05-18T17:21:36-04:00 HAIR-041 Step 50: Regenerate widget scaffolds from schema v2
 * Widget ID: admin.resource.bulk-action-bar
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type { Meta, StoryObj } from "@storybook/react";
import { BulkActionBar } from "./BulkActionBar";
import type { BulkActionBarProps } from "./BulkActionBar.types";

const defaultArgs = {
  tableId: "requests",
  rows: [{ id: "req_1" }, { id: "req_2" }],
  selectedRowIds: ["req_1"],
  actions: [{ type: "mutation", target: "requests.assign", label: "Assign" }],
} as unknown as BulkActionBarProps;

const meta = {
  title: "Admin DSL Widgets/Molecules/BulkActionBar",
  component: BulkActionBar,
  args: defaultArgs,
  parameters: {
    docs: {
      description: {
        component: "Owns the selected/visible-row action strip and visual hierarchy for table-level operations.",
      },
    },
  },
} satisfies Meta<typeof BulkActionBar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const VisibleRowsScope: Story = {
  name: "VisibleRowsScope",
  parameters: { docs: { description: { story: "Tests the VisibleRowsScope scenario for BulkActionBar with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <BulkActionBar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "visibleRowsScope"
}, asserts: [
  "BulkActionBar renders the VisibleRowsScope scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const SelectedRowsScope: Story = {
  name: "SelectedRowsScope",
  parameters: { docs: { description: { story: "Tests the SelectedRowsScope scenario for BulkActionBar with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <BulkActionBar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "selectedRowsScope"
}, asserts: [
  "BulkActionBar renders the SelectedRowsScope scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const PrimaryBulkAction: Story = {
  name: "PrimaryBulkAction",
  parameters: { docs: { description: { story: "Tests the PrimaryBulkAction scenario for BulkActionBar with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <BulkActionBar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "primaryBulkAction"
}, asserts: [
  "BulkActionBar renders the PrimaryBulkAction scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const DangerBulkAction: Story = {
  name: "DangerBulkAction",
  parameters: { docs: { description: { story: "Tests the DangerBulkAction scenario for BulkActionBar with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <BulkActionBar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "dangerBulkAction"
}, asserts: [
  "BulkActionBar renders the DangerBulkAction scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const NoSelectionDisabled: Story = {
  name: "NoSelectionDisabled",
  parameters: { docs: { description: { story: "Tests the NoSelectionDisabled scenario for BulkActionBar with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <BulkActionBar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "noSelectionDisabled"
}, asserts: [
  "BulkActionBar renders the NoSelectionDisabled scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
