/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T01:30:30+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/07-data-display-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.data-display.empty-state
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for EmptyState.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const emptyStateWidgetMetadata = {
  "widgetId": "admin.data-display.empty-state",
  "name": "EmptyState",
  "category": "data_display_widgets",
  "classification": {
    "level": "molecule",
    "description": "EmptyState participates in the Admin DSL component system as a molecule; its level controls scaffold location and Storybook grouping."
  },
  "purpose": "EmptyState widget.",
  "designRationale": "EmptyState extracts a named React boundary from the old Admin DSL renderer so behavior, stories, styling, and action context can be reviewed independently.",
  "adapterBoundary": "The Admin DSL adapter should convert raw node props/actions into typed EmptyState props. EmptyState should not parse AdminNode JSON or call backend dispatch helpers directly.",
  "implementationNotes": [
    "Implement EmptyState using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure EmptyState exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "primaryAction": {
      "doc": "primaryAction action slot for EmptyState. The widget emits the declared context through onAction and adapters lower it to runtime dispatch.",
      "callback": "onAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "PrimaryactionContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the primaryAction slot on EmptyState."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "Adapter lowers this typed callback into Admin DSL dispatch."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by EmptyState. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed EmptyState props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<EmptyState />"
    }
  },
  "stories": {
    "Default": {
      "doc": "Tests the baseline EmptyState rendering with representative production-like data.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "default"
      },
      "asserts": [
        "EmptyState renders the Default scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "WithAction": {
      "doc": "Tests single action rendering and callback wiring in EmptyState.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "withAction"
      },
      "asserts": [
        "EmptyState renders the WithAction scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"emptyState\""
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;
