/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: SplitPane
 * Category: layout_widgets
 * Classification: {"level": "organism"}
 * Current source inventory: case "splitPane"
 *
 * Human notes from YAML:
 * {
 *   "intent": "Encodes master/detail or two-column layouts explicitly. It should replace ad hoc gridTemplateColumns usage for split surfaces.",
 *   "adapter_boundary": "Adapter passes rendered left/right children in order; widget owns responsive stacking.",
 *   "storybook_intent": "Stories should prove master/detail, two panels, and mobile stacking."
 * }
 *
 * XXX items from YAML:
 * - XXX: Replace generated scaffold placeholder with final implementation.
 * - XXX: Keep raw Admin DSL JSON parsing in adapters, not in this widget.
 */
// XXX: Review this generated prop contract against the final widget implementation before relying on it as stable API.
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  PageActionHandler,
  PanelActionHandler,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

export interface SplitPaneProps extends CommonWidgetProps {
  leftWidth?: string;
  rightWidth?: string;
  gap?: number;
  children: React.ReactNode;
}
