/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T00:32:12+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.layout.split-pane
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for SplitPane.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const splitPaneWidgetMetadata = {
  "widgetId": "admin.layout.split-pane",
  "name": "SplitPane",
  "category": "layout_widgets",
  "classification": {
    "level": "organism",
    "description": "SplitPane participates in the Admin DSL component system as a organism; its level controls scaffold location and Storybook grouping."
  },
  "purpose": "Encodes master/detail or two-column layouts explicitly. It should replace ad hoc gridTemplateColumns usage for split surfaces.",
  "designRationale": "Encodes master/detail or two-column layouts explicitly. It should replace ad hoc gridTemplateColumns usage for split surfaces.",
  "adapterBoundary": "Adapter passes rendered left/right children in order; widget owns responsive stacking.",
  "implementationNotes": [
    "Implement SplitPane using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure SplitPane exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {},
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by SplitPane. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed SplitPane props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<SplitPane />"
    }
  },
  "stories": {
    "MasterDetail": {
      "doc": "Tests the MasterDetail scenario for SplitPane with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "masterDetail"
      },
      "asserts": [
        "SplitPane renders the MasterDetail scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "TwoPanels": {
      "doc": "Tests the TwoPanels scenario for SplitPane with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "twoPanels"
      },
      "asserts": [
        "SplitPane renders the TwoPanels scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "MobileStacked": {
      "doc": "Tests the MobileStacked scenario for SplitPane with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "mobileStacked"
      },
      "asserts": [
        "SplitPane renders the MobileStacked scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    },
    {
      "id": "keep-raw-admin-dsl-json-parsing-in-adapters-not-in-this-widget",
      "severity": "recommended",
      "doc": "Keep raw Admin DSL JSON parsing in adapters, not in this widget."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"splitPane\""
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;
