#!/usr/bin/env python3
"""Generate Admin DSL shared design-language helpers from IR YAML.

This script consumes ``15-design-language.yaml`` and writes shared TypeScript
helpers under ``web/src/admin-dsl/widgets/shared``. The generated files are meant
to be small, explicit projections of the design-language IR: they centralize
visual tokens, action variants, layout primitives, typography roles, and data
attribute helpers so promoted widgets do not copy style decisions independently.
"""

from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT_DEFAULT = Path(__file__).resolve().parents[6]
DEFAULT_INPUT = Path("ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/15-design-language.yaml")


def relpath(path: Path, repo_root: Path) -> str:
    try:
        return path.resolve().relative_to(repo_root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def git_last_commit(repo_root: Path, path: Path) -> str:
    try:
        rel = path.resolve().relative_to(repo_root.resolve())
    except ValueError:
        rel = path
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%h %cI %s", "--", rel.as_posix()],
            cwd=repo_root,
            check=False,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
        )
    except OSError:
        return "unknown (git unavailable)"
    return result.stdout.strip() or "none (untracked or no history)"


def header(repo_root: Path, script_path: Path, source: Path, target: Path, generated_at: str) -> str:
    return f'''/**
 * GENERATED DESIGN LANGUAGE — REVIEW BEFORE HAND EDITING.
 *
 * Generated by: {relpath(script_path, repo_root)}
 * Generated at: {generated_at}
 * Source YAML: {relpath(source, repo_root)}
 * Source YAML last commit: {git_last_commit(repo_root, source)}
 * Target file previous commit: {git_last_commit(repo_root, target)}
 *
 * This file is generated from Admin DSL Design Language IR. Update the YAML and
 * regenerate rather than editing this file directly unless explicitly promoting
 * it to hand-written code.
 */
'''


def out_path(data: dict[str, Any], key: str, repo_root: Path) -> Path:
    raw = data["outputs"][key]["path"]
    p = Path(raw)
    return p if p.is_absolute() else repo_root / p


def token_expr(value: Any) -> str:
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "undefined"
    text = str(value)
    if text.startswith(("color.", "font.", "radius.", "shadow.", "type.")):
        return text
    if text == "transparent":
        return json.dumps("transparent")
    return json.dumps(text)


def render_object(obj: dict[str, Any], indent: int = 2) -> str:
    pad = " " * indent
    lines = ["{"]
    for key, value in obj.items():
        if isinstance(value, dict):
            lines.append(f"{pad}{key}: {render_object(value, indent + 2)},")
        else:
            lines.append(f"{pad}{key}: {token_expr(value)},")
    lines.append(" " * (indent - 2) + "}")
    return "\n".join(lines)


def render_types(data: dict[str, Any], h: str) -> str:
    placements = sorted(data.get("action_placement_defaults", {}).keys())
    variants = sorted(data.get("action_variants", {}).keys())
    sizes = sorted(data.get("button_sizes", {}).keys())
    typography_roles = sorted(data.get("typography_roles", {}).keys())
    return h + f'''import type {{ CSSProperties, ReactNode }} from "react";

export type AdminActionPlacement = {" | ".join(json.dumps(x) for x in placements)};
export type AdminActionVariant = {" | ".join(json.dumps(x) for x in variants)};
export type AdminActionSize = {" | ".join(json.dumps(x) for x in sizes)};
export type AdminTypographyRole = {" | ".join(json.dumps(x) for x in typography_roles)};
export type AdminTone = "neutral" | "success" | "warning" | "danger" | "info" | "muted" | string;

export interface ActionViewModel {{
  id?: string;
  type: "open" | "close" | "navigate" | "mutation" | "confirm" | "refresh" | "upload" | string;
  target: string;
  label: string;
  intent?: "neutral" | "primary" | "danger" | string;
  priority?: "primary" | "secondary" | "tertiary" | string;
  presentation?: "button" | "icon" | "menuItem" | "overflow" | "link" | string;
  placement?: AdminActionPlacement | string;
  disabled?: boolean;
  loading?: boolean;
  accessibilityLabel?: string;
  requiresConfirmation?: boolean;
  confirmation?: {{
    title?: string;
    body?: string;
    confirmLabel?: string;
    cancelLabel?: string;
  }};
  [key: string]: unknown;
}}

export interface SidebarNavItem {{
  id: string;
  label: string;
  icon?: string;
  action?: ActionViewModel;
  [key: string]: unknown;
}}

export interface SidebarNavProps {{
  activeItemId?: string;
  items: SidebarNavItem[];
}}

export interface CommonWidgetProps {{
  id?: string;
  className?: string;
  style?: CSSProperties;
  density?: "compact" | "normal" | "spacious";
  tone?: AdminTone;
  dataAttributes?: Record<string, string | number | boolean | undefined>;
}}

export type ResourceTableColumnKind =
  | "text"
  | "badge"
  | "status"
  | "actions"
  | "image"
  | "date"
  | "number"
  | "boolean"
  | "dragHandle"
  | string;

export type OverlaySurfaceKind = "modal" | "drawer" | "popover" | "sheet" | string;

export interface PaginationModel {{
  page: number;
  total: number;
  actions?: ActionViewModel[];
}}

export type PageActionHandler = (action: ActionViewModel, context: {{ pageId?: string }}) => void;
export type PanelActionHandler = (action: ActionViewModel, context: {{ panelId?: string }}) => void;
export type TableRowActionHandler<Row> = (action: ActionViewModel, context: {{ tableId: string; row: Row; rowId?: string }}) => void;
export type TableBulkActionHandler<Row> = (action: ActionViewModel, context: {{ tableId: string; scope: "visible" | "selected" | "allMatching"; rows: Row[]; selectedRowIds: string[] }}) => void;
export type FormActionHandler<Values> = (action: ActionViewModel, context: {{ formId: string; values: Values }}) => void;
export type CalendarCellActionHandler = (action: ActionViewModel, context: {{ calendarId: string; date: string }}) => void;

export interface GeneratedStoryFixture {{
  scenario: string;
  [key: string]: unknown;
}}

export interface WidgetScaffoldDiagnostics {{
  widgetId: string;
  purpose: string;
  adapterBoundary?: string;
  implementationNotes: string[];
  accessibilityNotes: string[];
  actionSlots: Record<string, unknown>;
  examples: Record<string, unknown>;
}}

export type WidgetChildren = ReactNode;
'''


def render_design_tokens(data: dict[str, Any], h: str) -> str:
    sections = {}
    for section, values in data.get("token_aliases", {}).items():
        sections[section] = {name: item["token"] for name, item in values.items()}
    body = render_object(sections)
    return h + f'''import {{ color, radius }} from "../../../fringe-ui/tokens";

export const adminTokens = {body} as const;

export {{ color, font, radius, shadow, type }} from "../../../fringe-ui/tokens";
'''


def render_typography(data: dict[str, Any], h: str) -> str:
    roles = data.get("typography_roles", {})
    entries = []
    for name, spec in roles.items():
        base = spec.get("base", {})
        parts = []
        if isinstance(base, str):
            parts.append(f"...{base}")
        elif isinstance(base, dict):
            for key, value in base.items():
                parts.append(f"{key}: {token_expr(value)}")
        if spec.get("color"):
            parts.append(f"color: {token_expr(spec['color'])}")
        for key, value in (spec.get("overrides") or {}).items():
            parts.append(f"{key}: {token_expr(value)}")
        entries.append(f"  {name}: {{ {', '.join(parts)} }}")
    return h + f'''import type {{ CSSProperties }} from "react";
import {{ color, font, type }} from "../../../fringe-ui/tokens";
import type {{ AdminTypographyRole }} from "./types";

export const adminTypography = {{
{",\n".join(entries)}
}} satisfies Record<AdminTypographyRole, CSSProperties>;

export function adminTextStyle(role: AdminTypographyRole): CSSProperties {{
  return adminTypography[role];
}}
'''


def render_action_styles(data: dict[str, Any], h: str) -> str:
    return h + '''import type { CSSProperties } from "react";
import { color, font, radius, shadow } from "../../../fringe-ui/tokens";
import type { ActionViewModel, AdminActionPlacement, AdminActionSize, AdminActionVariant } from "./types";

export const actionPlacementDefaults = {
''' + "\n".join(
        f"  {name}: {{ defaultVariant: {json.dumps(spec['default_variant'])}, defaultSize: {json.dumps(spec['default_size'])} }},"
        for name, spec in data.get("action_placement_defaults", {}).items()
    ) + '''
} as const satisfies Record<string, { defaultVariant: AdminActionVariant; defaultSize: AdminActionSize }>;

export function actionPlacement(action: ActionViewModel, fallback: AdminActionPlacement = "toolbar"): AdminActionPlacement {
  return ((typeof action.placement === "string" && action.placement) || fallback) as AdminActionPlacement;
}

export function inferActionVariant(action: ActionViewModel, explicit?: AdminActionVariant, fallbackPlacement: AdminActionPlacement = "toolbar"): AdminActionVariant {
  if (explicit) return explicit;
  if (action.intent === "danger") return "danger";
  if (action.priority === "primary" || action.intent === "primary") {
    return actionPlacement(action, fallbackPlacement) === "formFooter" ? "formPrimary" : "solid";
  }
  if (action.presentation === "overflow" || actionPlacement(action, fallbackPlacement) === "rowOverflow") return "overflow";
  const placement = actionPlacement(action, fallbackPlacement);
  return actionPlacementDefaults[placement]?.defaultVariant ?? "soft";
}

export function inferActionSize(action: ActionViewModel, explicit?: AdminActionSize, fallbackPlacement: AdminActionPlacement = "toolbar"): AdminActionSize {
  if (explicit) return explicit;
  const placement = actionPlacement(action, fallbackPlacement);
  return actionPlacementDefaults[placement]?.defaultSize ?? "md";
}

export function actionButtonStyle(options: {
  variant: AdminActionVariant;
  size: AdminActionSize;
  disabled?: boolean;
  loading?: boolean;
}): CSSProperties {
  const { variant, size, disabled, loading } = options;
  const subtle = variant === "subtle" || variant === "overflow";
  const solid = variant === "solid";
  const danger = variant === "danger";
  const formPrimary = variant === "formPrimary";
  const minHeight = variant === "overflow" ? 32 : size === "touch" ? 44 : subtle ? 32 : size === "sm" ? 34 : 38;
  const padding = variant === "overflow" ? "6px 8px" : subtle ? "6px 8px" : size === "touch" ? "9px 14px" : size === "sm" ? "7px 10px" : "8px 12px";

  return {
    minHeight,
    minWidth: variant === "overflow" ? 32 : undefined,
    border: subtle ? "1px solid transparent" : `1px solid ${danger ? color.danger : solid ? color.ink : color.rule}`,
    background: disabled ? color.ruleSoft : subtle ? "transparent" : solid ? color.ink : formPrimary ? color.cream : color.paper,
    color: disabled ? color.soft : solid ? color.paper : danger ? color.danger : subtle ? color.plum : color.ink,
    borderRadius: radius.md,
    padding,
    fontFamily: subtle ? font.sans : font.mono,
    fontSize: subtle ? 13 : 11,
    letterSpacing: subtle ? 0 : 0.6,
    textTransform: subtle ? "none" : "uppercase",
    cursor: disabled || loading ? "not-allowed" : "pointer",
    opacity: loading ? 0.72 : 1,
    boxShadow: solid ? shadow.sm : "none",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    lineHeight: 1.15,
    fontWeight: subtle ? 500 : 700,
  };
}

export function sidebarNavButtonStyle(options: { active?: boolean; disabled?: boolean }): CSSProperties {
  const { active, disabled } = options;
  return {
    minHeight: 38,
    border: "none",
    borderRadius: radius.md,
    background: active ? "rgba(18, 17, 16, 0.07)" : "transparent",
    color: disabled ? color.soft : color.ink,
    display: "grid",
    gridTemplateColumns: "22px 1fr",
    alignItems: "center",
    gap: 10,
    padding: "8px 10px",
    textAlign: "left",
    cursor: disabled ? "default" : "pointer",
    fontFamily: font.sans,
    fontSize: 12,
    lineHeight: 1.4,
    fontWeight: active ? 800 : 500,
  };
}

export function shellMenuButtonStyle(): CSSProperties {
  return {
    ...actionButtonStyle({ variant: "soft", size: "sm" }),
    minHeight: 34,
  };
}
'''


def render_layout_styles(data: dict[str, Any], h: str) -> str:
    return h + '''import type { CSSProperties } from "react";
import { color, font, radius, shadow } from "../../../fringe-ui/tokens";

export const adminSurfaceStyle: CSSProperties = {
  background: color.paper,
  border: `1px solid ${color.rule}`,
  borderRadius: radius.lg,
  boxShadow: shadow.sm,
};

export function adminPageRootStyle(options: { shellKind?: string } = {}): CSSProperties {
  return {
    minHeight: "100vh",
    background: options.shellKind === "calendar" ? color.cream : color.creamDeep,
    color: color.ink,
    fontFamily: font.sans,
  };
}

export function adminActionRowStyle(options: { gap?: number; justifyContent?: CSSProperties["justifyContent"] } = {}): CSSProperties {
  return {
    display: "flex",
    gap: options.gap ?? 8,
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: options.justifyContent ?? "flex-start",
  };
}

export function adminShellGridStyle(options: { hasSide?: boolean; maxWidth?: number | string } = {}): CSSProperties {
  return {
    maxWidth: options.maxWidth ?? 1180,
    margin: "0 auto",
    display: "grid",
    ["--admin-dsl-grid-columns" as string]: options.hasSide ? "minmax(0, 1fr) 340px" : "1fr",
    gap: 20,
  };
}
'''


def render_data_attributes(data: dict[str, Any], h: str) -> str:
    return h + '''import type { ActionViewModel } from "./types";

export function dataAttrsFromRecord(values?: Record<string, string | number | boolean | undefined>): Record<string, string> {
  return Object.fromEntries(
    Object.entries(values ?? {})
      .filter(([, value]) => value !== undefined)
      .map(([key, value]) => [`data-${key}`, String(value)]),
  ) as Record<string, string>;
}

export function widgetDataAttributes(widgetId: string, level?: string): Record<string, string> {
  return {
    "data-admin-dsl-widget-id": widgetId,
    ...(level ? { "data-admin-dsl-widget-level": level } : {}),
  };
}

export function actionDataAttributes(action: ActionViewModel): Record<string, string | undefined> {
  return {
    "data-admin-dsl-action-intent": typeof action.intent === "string" ? action.intent : undefined,
    "data-admin-dsl-action-priority": typeof action.priority === "string" ? action.priority : undefined,
    "data-admin-dsl-action-placement": typeof action.placement === "string" ? action.placement : undefined,
    "data-admin-dsl-action-confirm": action.requiresConfirmation ? "true" : undefined,
  };
}
'''


def render_barrel(h: str) -> str:
    return h + '''export type * from "./types";
export * from "./designTokens";
export * from "./actionStyles";
export * from "./layoutStyles";
export * from "./typography";
export * from "./dataAttributes";
'''


def write(path: Path, content: str, dry_run: bool) -> None:
    if dry_run:
        print(f"WRITE {path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"WRITE {path}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT_DEFAULT)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    source = args.input if args.input.is_absolute() else repo_root / args.input
    data = yaml.safe_load(source.read_text())
    if data.get("artifact_type") != "admin_dsl_design_language_ir":
        raise SystemExit(f"unexpected artifact_type: {data.get('artifact_type')!r}")

    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    script_path = Path(__file__).resolve()
    outputs = {
        "shared_types": render_types,
        "design_tokens": render_design_tokens,
        "action_styles": render_action_styles,
        "layout_styles": render_layout_styles,
        "typography": render_typography,
        "data_attributes": render_data_attributes,
    }
    for key, renderer in outputs.items():
        target = out_path(data, key, repo_root)
        write(target, renderer(data, header(repo_root, script_path, source, target, generated_at)), args.dry_run)
    barrel = out_path(data, "barrel", repo_root)
    write(barrel, render_barrel(header(repo_root, script_path, source, barrel, generated_at)), args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
