/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T23:28:16+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: baf8866 2026-05-18T17:21:36-04:00 HAIR-041 Step 50: Regenerate widget scaffolds from schema v2
 * Widget ID: admin.layout.page-header
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

/**
 * Props for PageHeader. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface PageHeaderProps extends CommonWidgetProps {
  /**
   * Breadcrumb labels shown above the PageHeader title to communicate page hierarchy.
   */
  breadcrumbs?: string[];
  /**
   * Primary heading or title rendered by PageHeader.
   */
  title: string;
  /**
   * Optional descriptive text that explains the surrounding page or widget state.
   */
  description?: string;
  /**
   * High-level page actions rendered by PageHeader; these should be few and page-scoped.
   */
  primaryActions?: ActionViewModel[];
  /**
   * Callback for page-scoped primary actions emitted by PageHeader.
   */
  onPrimaryAction?: PageActionHandler;
}
