/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: PageHeader
 * Category: layout_widgets
 * Classification: {"level": "organism"}
 * Current source inventory: case "pageHeader" in renderAdminNode
 *
 * Human notes from YAML:
 * {
 *   "intent": "Owns page-level title hierarchy, breadcrumbs, description, and primary page actions. It should make the top-of-page layout reusable across workbench screens.",
 *   "adapter_boundary": "Adapter maps pageHeader props/actions into typed props; widget receives strings and ActionViewModel values only.",
 *   "slot_intent": {
 *     "primaryActions": "Page actions should be few and high-level. They should not receive row/form context."
 *   },
 *   "storybook_intent": "Stories should cover long responsive titles, breadcrumbs, descriptions, and primary action alignment."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "primaryActions",
 *     "context": "page",
 *     "callback_prop": "onPrimaryAction",
 *     "intent": "Page actions should be few and high-level. They should not receive row/form context.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Replace generated scaffold placeholder with final implementation.
 * - XXX: Keep raw Admin DSL JSON parsing in adapters, not in this widget.
 */
// XXX: Review this generated prop contract against the final widget implementation before relying on it as stable API.
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  PageActionHandler,
  PanelActionHandler,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

export interface PageHeaderProps extends CommonWidgetProps {
  breadcrumbs?: string[];
  title: string;
  description?: string;
  primaryActions?: ActionViewModel[];
  onPrimaryAction?: PageActionHandler;
}
