/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.resource.pagination-bar
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type { Meta, StoryObj } from "@storybook/react";
import { PaginationBar } from "./PaginationBar";
import type { PaginationBarProps } from "./PaginationBar.types";

const defaultArgs = {
  page: 1,
  total: 42,
  actions: [{ type: "navigate", target: "page.next", label: "Next" }],
} as unknown as PaginationBarProps;

const meta = {
  title: "Admin DSL Widgets/Molecules/PaginationBar",
  component: PaginationBar,
  args: defaultArgs,
  parameters: {
    docs: {
      description: {
        component: "Owns table paging footer and keeps paging actions separate from row/table bulk actions.",
      },
    },
  },
} satisfies Meta<typeof PaginationBar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  name: "Default",
  parameters: { docs: { description: { story: "Tests the baseline PaginationBar rendering with representative production-like data." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <PaginationBar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "default"
}, asserts: [
  "PaginationBar renders the Default scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const WithNextPrevious: Story = {
  name: "WithNextPrevious",
  parameters: { docs: { description: { story: "Tests the WithNextPrevious scenario for PaginationBar with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <PaginationBar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "withNextPrevious"
}, asserts: [
  "PaginationBar renders the WithNextPrevious scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const ManyResults: Story = {
  name: "ManyResults",
  parameters: { docs: { description: { story: "Tests the ManyResults scenario for PaginationBar with representative fixtures and assertions." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <PaginationBar {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "manyResults"
}, asserts: [
  "PaginationBar renders the ManyResults scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
