/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: PaginationBar
 * Category: resource_widgets
 * Classification: {"level": "molecule"}
 * Current source inventory: pagination footer inside resourceTable branch
 *
 * Human notes from YAML:
 * {
 *   "intent": "Owns table paging footer and keeps paging actions separate from row/table bulk actions.",
 *   "adapter_boundary": "Adapter passes page/total/action state. Widget should not know query params or backend transport.",
 *   "slot_intent": {
 *     "paginationActions": "Pagination actions carry page/total context and should be visually secondary."
 *   },
 *   "storybook_intent": "Stories should cover default, next/previous, and large-result displays."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "paginationActions",
 *     "context": "{ page, total }",
 *     "callback_prop": "onAction",
 *     "intent": "Pagination actions carry page/total context and should be visually secondary.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Define paging action payload contract before production use.
 */
// XXX: Replace generated defaultArgs with purposeful fixtures for every planned story before treating this as visual coverage.
import type { Meta, StoryObj } from "@storybook/react";
import { PaginationBar } from "./PaginationBar";
import type { PaginationBarProps } from "./PaginationBar.types";

const defaultArgs = {
  page: 1,
  total: 42,
  actions: [{ type: "navigate", target: "page.next", label: "Next" }],
} as unknown as PaginationBarProps;

const meta = {
  title: "Admin DSL Widgets/Molecules/PaginationBar",
  component: PaginationBar,
  args: defaultArgs,
} satisfies Meta<typeof PaginationBar>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const WithNextPrevious: Story = {};
export const ManyResults: Story = {};
