/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/06-resource-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: PaginationBar
 * Category: resource_widgets
 * Classification: {"level": "molecule"}
 * Current source inventory: pagination footer inside resourceTable branch
 *
 * Human notes from YAML:
 * {
 *   "intent": "Owns table paging footer and keeps paging actions separate from row/table bulk actions.",
 *   "adapter_boundary": "Adapter passes page/total/action state. Widget should not know query params or backend transport.",
 *   "slot_intent": {
 *     "paginationActions": "Pagination actions carry page/total context and should be visually secondary."
 *   },
 *   "storybook_intent": "Stories should cover default, next/previous, and large-result displays."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "paginationActions",
 *     "context": "{ page, total }",
 *     "callback_prop": "onAction",
 *     "intent": "Pagination actions carry page/total context and should be visually secondary.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Define paging action payload contract before production use.
 */
// XXX: Review this generated prop contract against the final widget implementation before relying on it as stable API.
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  PageActionHandler,
  PanelActionHandler,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../../../shared/types";

export interface PaginationBarProps {
  page: number;
  total: number;
  actions?: ActionViewModel[];
  onAction?: (action: ActionViewModel, context: { page: number; total: number }) => void;
}
