/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/10a-form-field-widgets.yaml
 * Widget ID: admin.form-field.switch-field
 *
 * Manual edits after generation:
 * - 2026-05-19 / HAIR-041 Step 126: Added explicit boolean callback contract for promoted switchField leaf.
 */
import type { ChangeEventHandler } from "react";
import type { CommonWidgetProps } from "../../shared/types";

export interface SwitchFieldProps extends CommonWidgetProps {
  name: string;
  label: string;
  checked?: boolean;
  helpText?: string;
  error?: string;
  disabled?: boolean;
  readOnly?: boolean;
  required?: boolean;
  onValueChange?: (checked: boolean, event: Parameters<ChangeEventHandler<HTMLInputElement>>[0]) => void;
}
