/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/11-surface-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.surface.confirm-dialog
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";

/**
 * Props for ConfirmDialog. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface ConfirmDialogProps extends CommonWidgetProps {
  /**
   * dialogId configures confirm dialog. Type: string.
   */
  dialogId: string;
  /**
   * Primary heading or title rendered by ConfirmDialog.
   */
  title: string;
  /**
   * Optional body copy rendered by ConfirmDialog.
   */
  body?: string;
  /**
   * Visual tone used for status, emphasis, or border treatment in ConfirmDialog.
   */
  tone?: "neutral" | "danger";
  /**
   * confirmLabel configures confirm dialog. Type: string.
   */
  confirmLabel?: string;
  /**
   * confirmAction configures confirm dialog. Type: ActionViewModel.
   */
  confirmAction?: ActionViewModel;
  /**
   * cancelAction configures confirm dialog. Type: ActionViewModel.
   */
  cancelAction?: ActionViewModel;
  /**
   * onConfirm configures confirm dialog. Type: (action: ActionViewModel, context: { dialogId: string }) => void.
   */
  onConfirm?: (action: ActionViewModel, context: { dialogId: string }) => void;
  /**
   * onCancel configures confirm dialog. Type: (action: ActionViewModel, context: { dialogId: string }) => void.
   */
  onCancel?: (action: ActionViewModel, context: { dialogId: string }) => void;
}
