/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-19T04:31:57+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/11-surface-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.surface.confirm-dialog
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
/**
 * Widget IR metadata for ConfirmDialog.
 *
 * Keep this file next to the implementation even after replacing generated
 * scaffolds with hand-written code. It preserves the source intent, adapter
 * boundary, action-slot contract, examples, stories, and implementation notes
 * that explain why the component exists and how render adapters should use it.
 */
export const confirmDialogWidgetMetadata = {
  "widgetId": "admin.surface.confirm-dialog",
  "name": "ConfirmDialog",
  "category": "surface_widgets",
  "classification": {
    "level": "organism",
    "description": "ConfirmDialog participates in the Admin DSL component system as a organism; its level controls scaffold location and Storybook grouping."
  },
  "purpose": "ConfirmDialog widget.",
  "designRationale": "ConfirmDialog extracts a named React boundary from the old Admin DSL renderer so behavior, stories, styling, and action context can be reviewed independently.",
  "adapterBoundary": "The Admin DSL adapter should convert raw node props/actions into typed ConfirmDialog props. ConfirmDialog should not parse AdminNode JSON or call backend dispatch helpers directly.",
  "implementationNotes": [
    "Implement ConfirmDialog using design tokens and typed props from this IR.",
    "Keep transport/adapter compatibility outside the visual component."
  ],
  "accessibilityNotes": [
    "Ensure ConfirmDialog exposes semantic roles, labels, focus behavior, and keyboard interaction appropriate to its rendered controls."
  ],
  "actionSlots": {
    "confirm": {
      "doc": "confirm action slot for ConfirmDialog. The widget emits the declared context through onAction and adapters lower it to runtime dispatch.",
      "callback": "onAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "ConfirmContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the confirm slot on ConfirmDialog."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "Adapter lowers this typed callback into Admin DSL dispatch."
      }
    },
    "cancel": {
      "doc": "cancel action slot for ConfirmDialog. The widget emits the declared context through onAction and adapters lower it to runtime dispatch.",
      "callback": "onAction",
      "action_type": "ActionViewModel",
      "cardinality": "many",
      "context_type": "CancelContext",
      "context": {
        "value": {
          "type": "unknown",
          "required": false,
          "doc": "Optional contextual payload for the cancel slot on ConfirmDialog."
        }
      },
      "lowering": {
        "adapter": "dispatchAdminAction",
        "note": "Adapter lowers this typed callback into Admin DSL dispatch."
      }
    }
  },
  "examples": {
    "BasicUsage": {
      "doc": "Demonstrates the normalized props expected by ConfirmDialog. Use this as a scaffold for real stories and implementation tests.",
      "demonstrates": [
        "Typed ConfirmDialog props after adapter lowering.",
        "Widget-level usage without raw Admin DSL parsing."
      ],
      "code": "<ConfirmDialog />"
    }
  },
  "stories": {
    "Default": {
      "doc": "Tests the baseline ConfirmDialog rendering with representative production-like data.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "default"
      },
      "asserts": [
        "ConfirmDialog renders the Default scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "Danger": {
      "doc": "Tests danger/destructive action treatment for ConfirmDialog.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "danger"
      },
      "asserts": [
        "ConfirmDialog renders the Danger scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "LongBody": {
      "doc": "Tests the LongBody scenario for ConfirmDialog with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "longBody"
      },
      "asserts": [
        "ConfirmDialog renders the LongBody scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "WithCancel": {
      "doc": "Tests the WithCancel scenario for ConfirmDialog with representative fixtures and assertions.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "withCancel"
      },
      "asserts": [
        "ConfirmDialog renders the WithCancel scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    },
    "DispatchConfirm": {
      "doc": "Tests confirm callback context in ConfirmDialog.",
      "viewport": "desktop",
      "fixtures": {
        "scenario": "dispatchConfirm"
      },
      "asserts": [
        "ConfirmDialog renders the DispatchConfirm scenario without layout breakage.",
        "The relevant semantic state is visible to users and test selectors."
      ]
    }
  },
  "implementationTodos": [
    {
      "id": "replace-generated-scaffold-placeholder-with-final-implementation",
      "severity": "required",
      "doc": "Replace generated scaffold placeholder with final implementation."
    }
  ],
  "sourceMapping": {
    "current_constructs": [
      "case \"confirmDialog\""
    ],
    "current_files": [
      {
        "path": "web/src/admin-dsl/render.tsx",
        "notes": "Current renderer source to inspect for this construct."
      }
    ]
  }
} as const;
