/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: dfc6ac6 2026-05-18T16:41:42-04:00 HAIR-041 Step 44: Scaffold Admin DSL widgets from IR
 * Widget ID: admin.layout.tabs
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
export { Tabs } from "./Tabs";
export type * from "./Tabs.types";
