/**
 * GENERATED SCAFFOLD — DO NOT TREAT AS FINISHED IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T20:40:03+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/05-layout-widgets.yaml
 * Source YAML last commit: ec60525 2026-05-18T16:21:43-04:00 HAIR-041 Step 43: Add widget IR YAML artifacts
 * Target file previous commit: none (untracked or no history)
 *
 * This header is the first changelog entry for this generated scaffold. When a
 * human replaces generated placeholders, keep the generated provenance above and
 * add implementation notes below it rather than deleting the history.
 */
/**
 * Widget IR: Tabs
 * Category: layout_widgets
 * Classification: {"level": "molecule"}
 * Current source inventory: case "tabs"
 *
 * Human notes from YAML:
 * {
 *   "intent": "Represents tab choice as a compact control with active state and optional action dispatch.",
 *   "adapter_boundary": "Adapter maps tabs/value/action props; widget emits selected tab context through onTabChange.",
 *   "slot_intent": {
 *     "tabChange": "Tab changes are selection actions with tab context; they should not be modeled as row actions."
 *   },
 *   "storybook_intent": "Stories should cover active, readonly, action-backed, and wrapping states."
 * }
 *
 * Action slots / callback intent:
 * [
 *   {
 *     "name": "tabChange",
 *     "callback_prop": "onTabChange",
 *     "intent": "Tab changes are selection actions with tab context; they should not be modeled as row actions.",
 *     "implementation_note": "The widget emits typed context through the callback; the Admin DSL adapter lowers it to dispatchAdminAction or backend action transport."
 *   }
 * ]
 *
 * XXX items from YAML:
 * - XXX: Replace generated scaffold placeholder with final implementation.
 * - XXX: Keep raw Admin DSL JSON parsing in adapters, not in this widget.
 */
// XXX: Replace generated defaultArgs with purposeful fixtures for every planned story before treating this as visual coverage.
import type { Meta, StoryObj } from "@storybook/react";
import { Tabs } from "./Tabs";
import type { TabsProps } from "./Tabs.types";

const defaultArgs = {
  tabs: [{ id: "all", label: "All" }, { id: "open", label: "Open" }],
  value: "all",
} as unknown as TabsProps;

const meta = {
  title: "Admin DSL Widgets/Molecules/Tabs",
  component: Tabs,
  args: defaultArgs,
} satisfies Meta<typeof Tabs>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {};
export const ActiveTab: Story = {};
export const NoActionReadonly: Story = {};
export const WrappingMobile: Story = {};
