/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/09-calendar-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.calendar.calendar-week
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type { Meta, StoryObj } from "@storybook/react";
import { CalendarWeek } from "./CalendarWeek";
import type { CalendarWeekProps } from "./CalendarWeek.types";

const defaultArgs = {
  calendarId: "schedule",
  days: ["Mon", "Tue", "Wed"],
  hours: ["09:00", "10:00"],
  blocks: [],
} as unknown as CalendarWeekProps;

const meta = {
  title: "Admin DSL Widgets/Organisms/CalendarWeek",
  component: CalendarWeek,
  args: defaultArgs,
  parameters: {
    docs: {
      description: {
        component: "CalendarWeek widget.",
      },
    },
  },
} satisfies Meta<typeof CalendarWeek>;

export default meta;
type Story = StoryObj<typeof meta>;

export const DefaultWeek: Story = {
  name: "DefaultWeek",
  parameters: { docs: { description: { story: "Tests the normal week grid and block placement for CalendarWeek." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <CalendarWeek {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "defaultWeek"
}, asserts: [
  "CalendarWeek renders the DefaultWeek scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const AppointmentsAndTimeOff: Story = {
  name: "AppointmentsAndTimeOff",
  parameters: { docs: { description: { story: "Tests mixed appointment/time-off rendering in CalendarWeek." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <CalendarWeek {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "appointmentsAndTimeOff"
}, asserts: [
  "CalendarWeek renders the AppointmentsAndTimeOff scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const NoAppointments: Story = {
  name: "NoAppointments",
  parameters: { docs: { description: { story: "Tests empty calendar week rendering in CalendarWeek." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <CalendarWeek {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "noAppointments"
}, asserts: [
  "CalendarWeek renders the NoAppointments scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const MobileAgenda: Story = {
  name: "MobileAgenda",
  parameters: { docs: { description: { story: "Tests mobile agenda fallback for CalendarWeek." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <CalendarWeek {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "mobileAgenda"
}, asserts: [
  "CalendarWeek renders the MobileAgenda scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
export const LongDayLabels: Story = {
  name: "LongDayLabels",
  parameters: { docs: { description: { story: "Tests long day labels and horizontal spacing in CalendarWeek." } } },
  args: {
    ...defaultArgs,
  },
  render: (args) => (
    <div style={{ padding: 24, maxWidth: 1120 }}>
      <CalendarWeek {...args} />
      <details style={{ marginTop: 12, fontSize: 12, color: "#6f6254" }}>
        <summary>Story fixture and assertions</summary>
        <pre style={{ whiteSpace: "pre-wrap" }}>{JSON.stringify({ fixtures: {
  "scenario": "longDayLabels"
}, asserts: [
  "CalendarWeek renders the LongDayLabels scenario without layout breakage.",
  "The relevant semantic state is visible to users and test selectors."
] }, null, 2)}</pre>
      </details>
    </div>
  ),
};
