/**
 * GENERATED SCAFFOLD — REVIEW BEFORE PROMOTING TO FINAL IMPLEMENTATION.
 *
 * Generated by: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/scripts/05-scaffold-admin-dsl-widgets.py
 * Generated at: 2026-05-18T21:21:08+00:00
 * Source YAML: ttmp/2026/05/15/HAIR-041--real-admin-backend-for-intake-app/sources/admin-dsl-widget-ir/09-calendar-widgets.yaml
 * Source YAML last commit: e555038 2026-05-18T17:11:02-04:00 HAIR-041 Step 48: Fill widget IR YAML intent
 * Target file previous commit: none (untracked or no history)
 * Widget ID: admin.calendar.calendar-week
 *
 * This file is generated from schema-v2 Widget Definition IR. Keep raw Admin DSL
 * JSON decoding in adapters; generated widgets should receive typed props only.
 */
import type * as React from "react";
import type {
  ActionViewModel,
  CalendarCellActionHandler,
  CommonWidgetProps,
  FormActionHandler,
  OverlaySurfaceKind,
  PageActionHandler,
  PanelActionHandler,
  ResourceTableColumnKind,
  SidebarNavItem,
  SidebarNavProps,
  TableBulkActionHandler,
  TableRowActionHandler,
} from "../../shared/types";
import type { CalendarEventBlockProps } from "../../molecules/CalendarEventBlock/CalendarEventBlock.types";

/**
 * Props for CalendarWeek. These are normalized widget props produced by adapters or callers, not raw Admin DSL JSON.
 */
export interface CalendarWeekProps extends CommonWidgetProps {
  /**
   * calendarId configures calendar week. Type: string.
   */
  calendarId: string;
  /**
   * days configures calendar week. Type: string[].
   */
  days: string[];
  /**
   * hours configures calendar week. Type: string[].
   */
  hours: string[];
  /**
   * blocks configures calendar week. Type: CalendarEventBlockProps[].
   */
  blocks: CalendarEventBlockProps[];
  /**
   * onBlockAction configures calendar week. Type: (action: ActionViewModel, context: { block: CalendarEventBlockProps }) => void.
   */
  onBlockAction?: (action: ActionViewModel, context: { block: CalendarEventBlockProps }) => void;
}
